import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  viewShot: { ...StyleSheet.absoluteFillObject },
  camera: { ...StyleSheet.absoluteFillObject },
  controls: { ...StyleSheet.absoluteFillObject, zIndex: 20 },
  backButton: {
    position: "absolute",
    top: 52,
    left: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  backButtonText: { color: "#FFF", fontSize: 18, fontWeight: "700" },

  faceDetectedBadge: {
    position: "absolute",
    top: 56,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(6,182,212,0.3)",
  },
  faceDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "#06B6D4" },
  faceDetectedText: {
    color: "#06B6D4",
    fontSize: 10,
    fontWeight: "700",
    fontFamily: "monospace",
    letterSpacing: 1.5,
  },

  scanButtonArea: {
    position: "absolute",
    bottom: 120,
    alignSelf: "center",
    alignItems: "center",
  },
  scanButton: {
    backgroundColor: "rgba(168,85,247,0.85)",
    borderRadius: 30,
    paddingHorizontal: 36,
    paddingVertical: 16,
    borderWidth: 2,
    borderColor: "rgba(168,85,247,0.5)",
    shadowColor: "#A855F7",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 12,
  },
  scanButtonDisabled: {
    backgroundColor: "rgba(80,80,100,0.5)",
    borderColor: "rgba(80,80,100,0.3)",
    shadowOpacity: 0,
    elevation: 0,
  },
  scanButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "800",
    fontFamily: "monospace",
    letterSpacing: 3,
  },
  scanHint: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 11,
    marginTop: 10,
    fontFamily: "monospace",
    letterSpacing: 0.5,
    textAlign: "center",
  },

  progressContainer: {
    position: "absolute",
    top: 56,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  progressTrack: {
    width: 160,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.1)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#A855F7",
    borderRadius: 2,
  },
  progressText: {
    color: "#A855F7",
    fontSize: 11,
    fontWeight: "700",
    fontFamily: "monospace",
    width: 36,
  },

  scanningBadge: {
    position: "absolute",
    bottom: 130,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.55)",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(168,85,247,0.3)",
  },
  scanDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#A855F7" },
  scanningText: {
    color: "#A855F7",
    fontSize: 10,
    fontWeight: "700",
    fontFamily: "monospace",
    letterSpacing: 1.5,
  },

  resultHeader: {
    position: "absolute",
    top: 50,
    alignSelf: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(168,85,247,0.3)",
  },
  resultTitle: {
    color: "#E8F0FF",
    fontSize: 13,
    fontWeight: "800",
    fontFamily: "monospace",
    letterSpacing: 2,
  },
  resultSubtitle: {
    color: "#A855F7",
    fontSize: 12,
    fontWeight: "600",
    fontFamily: "monospace",
    marginTop: 2,
  },

  rescanButtonArea: {
    position: "absolute",
    bottom: 120,
    alignSelf: "center",
    alignItems: "center",
  },
  resultActions: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  rescanButton: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 24,
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderWidth: 1.5,
    borderColor: "rgba(168,85,247,0.5)",
  },
  rescanButtonText: {
    color: "#A855F7",
    fontSize: 14,
    fontWeight: "700",
    fontFamily: "monospace",
    letterSpacing: 2,
  },
  captureButton: {
    backgroundColor: "rgba(168,85,247,0.85)",
    borderRadius: 24,
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderWidth: 1.5,
    borderColor: "rgba(168,85,247,0.7)",
    shadowColor: "#A855F7",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 8,
  },
  captureButtonDisabled: {
    backgroundColor: "rgba(80,80,100,0.5)",
    borderColor: "rgba(80,80,100,0.3)",
    shadowOpacity: 0,
    elevation: 0,
  },
  captureButtonText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "700",
    fontFamily: "monospace",
    letterSpacing: 2,
  },

  permissionContainer: {
    flex: 1,
    backgroundColor: "#050A15",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
    gap: 16,
  },
  permissionTitle: {
    color: "#E8F0FF",
    fontSize: 20,
    fontWeight: "700",
    textAlign: "center",
  },
  permissionText: {
    color: "#7B93B8",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  permissionButton: {
    backgroundColor: "#A855F7",
    borderRadius: 12,
    paddingHorizontal: 28,
    paddingVertical: 14,
    marginTop: 8,
  },
  permissionButtonText: {
    color: "#FFF",
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 1,
  },
  backLink: { marginTop: 12 },
  backLinkText: {
    color: "#4A6080",
    fontSize: 13,
    fontFamily: "monospace",
    letterSpacing: 1,
  },
});
