import type { SeededPerson } from "./index";

import { INVESTORS_EXTRA_SEED } from "./02b-person-investor-extra.seed";

export const INVESTORS_SEED: SeededPerson[] = [
  {
    name: "Ray Dalio",
    birthday: "1949-08-08",
    categories: ["investor"],
    tags: ["hedge_fund", "finance", "asset_management"],
    nationality: "American",
    title: "Founder of Bridgewater Associates",
    description:
      "Founder of Bridgewater, the world's largest hedge fund with ~$150B AUM, known for macro-economic analysis.",
    imageUrl: null,
    wikidataId: "Q3394874",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ray_Dalio",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "George Soros",
    birthday: "1930-08-12",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "Founder of Soros Fund Management",
    description:
      "Legendary investor known as 'The Man Who Broke the Bank of England', founder of Open Society Foundations.",
    imageUrl: null,
    wikidataId: "Q12908",
    wikipediaUrl: "https://en.wikipedia.org/wiki/George_Soros",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Carl Icahn",
    birthday: "1936-02-16",
    categories: ["investor"],
    tags: ["finance", "private_equity"],
    nationality: "American",
    title: "Founder of Icahn Enterprises",
    description:
      "Pioneer of activist investing, known for hostile takeovers and corporate restructuring.",
    imageUrl: null,
    wikidataId: "Q2609",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Carl_Icahn",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Cathie Wood",
    birthday: "1955-11-26",
    categories: ["investor"],
    tags: ["asset_management", "tech", "ai"],
    nationality: "American",
    title: "CEO of ARK Invest",
    description:
      "CEO of ARK Invest, a leading thematic ETF firm focused on disruptive innovation and AI.",
    imageUrl: null,
    wikidataId: "Q60852764",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Cathie_Wood",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Michael Burry",
    birthday: "1971-06-19",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "Founder of Scion Asset Management",
    description:
      "Investor famous for predicting the 2008 subprime mortgage crisis, subject of 'The Big Short'.",
    imageUrl: null,
    wikidataId: "Q3308514",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Michael_Burry",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Bill Ackman",
    birthday: "1966-05-11",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "CEO of Pershing Square Capital",
    description:
      "Activist investor and CEO of Pershing Square Capital, known for high-conviction public bets.",
    imageUrl: null,
    wikidataId: "Q812331",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Bill_Ackman",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Stanley Druckenmiller",
    birthday: "1953-06-14",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "Founder of Duquesne Capital",
    description:
      "Legendary macro investor, former lead portfolio manager for Soros, never had a losing year.",
    imageUrl: null,
    wikidataId: "Q3497389",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Stanley_Druckenmiller",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "David Tepper",
    birthday: "1957-09-11",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "Founder of Appaloosa Management",
    description:
      "Founder of Appaloosa Management, one of the most successful distressed-debt investors in history.",
    imageUrl: null,
    wikidataId: "Q5238929",
    wikipediaUrl: "https://en.wikipedia.org/wiki/David_Tepper",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Steve Cohen",
    birthday: "1956-06-11",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "Founder of Point72 Asset Management",
    description:
      "Founder of Point72 (formerly SAC Capital), one of the most profitable quantitative hedge funds.",
    imageUrl: null,
    wikidataId: "Q7542283",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Steven_A._Cohen",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Paul Tudor Jones",
    birthday: "1954-09-28",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "Founder of Tudor Investment Corp",
    description:
      "Legendary macro trader who predicted the 1987 crash, pioneer of modern hedge fund strategies.",
    imageUrl: null,
    wikidataId: "Q2066119",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Paul_Tudor_Jones",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "John Paulson",
    birthday: "1955-12-14",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "Founder of Paulson & Co.",
    description:
      "Made the greatest trade in history by shorting subprime mortgages in 2007, earning $15B.",
    imageUrl: null,
    wikidataId: "Q1389684",
    wikipediaUrl: "https://en.wikipedia.org/wiki/John_Paulson",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "David Shaw",
    birthday: "1951-03-21",
    categories: ["investor"],
    tags: ["hedge_fund", "tech", "ai"],
    nationality: "American",
    title: "Founder of D.E. Shaw & Co.",
    description:
      "Founder of D.E. Shaw, a pioneering quantitative hedge fund, former Columbia University professor.",
    imageUrl: null,
    wikidataId: "Q5241072",
    wikipediaUrl: "https://en.wikipedia.org/wiki/David_E._Shaw",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Daniel Loeb",
    birthday: "1961-12-18",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "CEO of Third Point LLC",
    description:
      "Activist investor and founder of Third Point, known for aggressive public campaigns against companies.",
    imageUrl: null,
    wikidataId: "Q2615018",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Daniel_S._Loeb",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Seth Klarman",
    birthday: "1957-05-21",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "CEO of Baupost Group",
    description:
      "CEO of Baupost Group, the 'Oracle of Boston', author of the legendary 'Margin of Safety' investing book.",
    imageUrl: null,
    wikidataId: "Q7457181",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Seth_Klarman",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Chris Hohn",
    birthday: "1966-10-07",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "British",
    title: "Founder of TCI Fund Management",
    description:
      "Founder of TCI, one of Europe's most successful hedge funds known for activist and long-term strategies.",
    imageUrl: null,
    wikidataId: "Q5105777",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Chris_Hohn",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Alan Howard",
    birthday: "1963-09-29",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "British",
    title: "Co-founder of Brevan Howard",
    description:
      "Co-founder of Brevan Howard, one of Europe's largest macro hedge funds managing ~$30B.",
    imageUrl: null,
    wikidataId: "Q381803",
    wikipediaUrl:
      "https://en.wikipedia.org/wiki/Alan_Howard_(hedge_fund_manager)",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "David Einhorn",
    birthday: "1968-11-20",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "Founder of Greenlight Capital",
    description:
      "Founder of Greenlight Capital, famous for shorting Lehman Brothers before its collapse.",
    imageUrl: null,
    wikidataId: "Q5231428",
    wikipediaUrl: "https://en.wikipedia.org/wiki/David_Einhorn_(investor)",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Bruce Kovner",
    birthday: "1945-05-25",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "Founder of Caxton Associates",
    description:
      "Founder of Caxton Associates, legendary macro trader and one of the most successful hedge fund managers.",
    imageUrl: null,
    wikidataId: "Q4978547",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Bruce_Kovner",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Paul Singer",
    birthday: "1944-08-22",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "Founder of Elliott Management",
    description:
      "Founder of Elliott Management, one of the world's most feared activist hedge funds.",
    imageUrl: null,
    wikidataId: "Q2062001",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Paul_Singer_(businessman)",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Israel Englander",
    birthday: "1948-08-06",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "Founder of Millennium Management",
    description:
      "Founder of Millennium Management, a multi-strategy hedge fund managing over $60B in assets.",
    imageUrl: null,
    wikidataId: "Q6085636",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Israel_Englander",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Cliff Asness",
    birthday: "1966-10-12",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "American",
    title: "Co-founder of AQR Capital Management",
    description:
      "Co-founder of AQR, a quantitative investment firm managing ~$100B, trained under Eugene Fama.",
    imageUrl: null,
    wikidataId: "Q5131895",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Cliff_Asness",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Andreas Halvorsen",
    birthday: "1961-06-02",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "Norwegian",
    title: "Co-founder of Viking Global Investors",
    description:
      "Co-founder of Viking Global, a Tiger Cub hedge fund consistently ranked among the top performers.",
    imageUrl: null,
    wikidataId: "Q4755835",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Andreas_Halvorsen",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Michael Platt",
    birthday: "1968-03-06",
    categories: ["investor"],
    tags: ["hedge_fund", "finance"],
    nationality: "British",
    title: "Founder of BlueCrest Capital",
    description:
      "Founder of BlueCrest Capital Management, formerly one of Europe's largest hedge funds.",
    imageUrl: null,
    wikidataId: "Q6831988",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Michael_Platt_(financier)",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Henry Kravis",
    birthday: "1944-01-06",
    categories: ["investor"],
    tags: ["private_equity", "finance"],
    nationality: "American",
    title: "Co-founder of KKR & Co.",
    description:
      "Co-founder of KKR, pioneer of the leveraged buyout industry that transformed corporate America.",
    imageUrl: null,
    wikidataId: "Q1609016",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Henry_Kravis",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "David Rubenstein",
    birthday: "1949-08-11",
    categories: ["investor"],
    tags: ["private_equity", "finance"],
    nationality: "American",
    title: "Co-founder of The Carlyle Group",
    description:
      "Co-founder of Carlyle Group, one of the world's largest PE firms with over $400B in AUM.",
    imageUrl: null,
    wikidataId: "Q5236891",
    wikipediaUrl: "https://en.wikipedia.org/wiki/David_Rubenstein",
    source: "manual",
    sourceUrl: null,
  },
  ...INVESTORS_EXTRA_SEED,
];
