import type { SeededPerson } from "./index";

export const INVESTORS_EXTRA_SEED: SeededPerson[] = [
  {
    name: "Leon Black",
    birthday: "1951-07-31",
    categories: ["investor"],
    tags: ["private_equity", "finance"],
    nationality: "American",
    title: "Co-founder of Apollo Global Management",
    description:
      "Co-founder of Apollo Global Management, a leading alternative investment firm with $600B+ in AUM.",
    imageUrl: null,
    wikidataId: "Q6524377",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Leon_Black",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Nelson Peltz",
    birthday: "1942-06-24",
    categories: ["investor"],
    tags: ["finance", "private_equity"],
    nationality: "American",
    title: "Founder of Trian Fund Management",
    description:
      "Activist investor who has waged proxy battles at Disney, P&G, and other major corporations.",
    imageUrl: null,
    wikidataId: "Q2492920",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Nelson_Peltz",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Orlando Bravo",
    birthday: "1970-07-05",
    categories: ["investor"],
    tags: ["private_equity", "tech"],
    nationality: "American",
    title: "Co-founder of Thoma Bravo",
    description:
      "Co-founder of Thoma Bravo, the largest software-focused PE firm with $130B+ in AUM.",
    imageUrl: null,
    wikidataId: "Q85766997",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Orlando_Bravo",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Robert F. Smith",
    birthday: "1962-12-01",
    categories: ["investor"],
    tags: ["private_equity", "tech"],
    nationality: "American",
    title: "Founder of Vista Equity Partners",
    description:
      "Founder of Vista Equity Partners, wealthiest African American, enterprise software PE specialist.",
    imageUrl: null,
    wikidataId: "Q7344791",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Robert_F._Smith_(investor)",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Peter Thiel",
    birthday: "1967-10-11",
    categories: ["investor"],
    tags: ["venture_capital", "tech"],
    nationality: "American",
    title: "Co-founder of PayPal & Palantir",
    description:
      "Co-founder of PayPal and Palantir, first outside investor in Facebook, influential libertarian VC.",
    imageUrl: null,
    wikidataId: "Q312399",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Peter_Thiel",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Marc Andreessen",
    birthday: "1971-07-09",
    categories: ["investor"],
    tags: ["venture_capital", "tech"],
    nationality: "American",
    title: "Co-founder of Andreessen Horowitz",
    description:
      "Co-founder of a16z (Andreessen Horowitz), Netscape inventor who became Silicon Valley's top VC.",
    imageUrl: null,
    wikidataId: "Q337856",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Marc_Andreessen",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Vinod Khosla",
    birthday: "1955-01-28",
    categories: ["investor"],
    tags: ["venture_capital", "tech", "energy"],
    nationality: "American",
    title: "Founder of Khosla Ventures",
    description:
      "Co-founder of Sun Microsystems turned cleantech VC, investing in AI, biotech, and sustainability.",
    imageUrl: null,
    wikidataId: "Q1128297",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Vinod_Khosla",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Reid Hoffman",
    birthday: "1967-08-05",
    categories: ["investor"],
    tags: ["venture_capital", "tech", "ai"],
    nationality: "American",
    title: "Co-founder of LinkedIn & Greylock Partner",
    description:
      "LinkedIn co-founder turned top VC at Greylock Partners, early investor in Facebook and Airbnb.",
    imageUrl: null,
    wikidataId: "Q2451959",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Reid_Hoffman",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "John Doerr",
    birthday: "1951-06-29",
    categories: ["investor"],
    tags: ["venture_capital", "tech", "energy"],
    nationality: "American",
    title: "Chairman of Kleiner Perkins",
    description:
      "Chairman of Kleiner Perkins, backed Google, Amazon, and pioneered cleantech VC investing.",
    imageUrl: null,
    wikidataId: "Q528816",
    wikipediaUrl: "https://en.wikipedia.org/wiki/John_Doerr",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Chamath Palihapitiya",
    birthday: "1976-09-03",
    categories: ["investor"],
    tags: ["venture_capital", "tech"],
    nationality: "Canadian",
    title: "Founder of Social Capital",
    description:
      "Former Facebook executive turned VC and SPAC pioneer, vocal tech investor and media personality.",
    imageUrl: null,
    wikidataId: "Q5071603",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Chamath_Palihapitiya",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Bill Gurley",
    birthday: "1966-05-10",
    categories: ["investor"],
    tags: ["venture_capital", "tech"],
    nationality: "American",
    title: "General Partner at Benchmark",
    description:
      "Benchmark Capital partner, led the Uber investment and is one of Silicon Valley's most respected VCs.",
    imageUrl: null,
    wikidataId: "Q4911399",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Bill_Gurley",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Howard Marks",
    birthday: "1946-04-23",
    categories: ["investor"],
    tags: ["finance", "private_equity"],
    nationality: "American",
    title: "Co-founder of Oaktree Capital",
    description:
      "Co-founder of Oaktree Capital, renowned distressed-debt investor whose memos are must-reads on Wall Street.",
    imageUrl: null,
    wikidataId: "Q5922058",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Howard_Marks_(investor)",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Mary Callahan Erdoes",
    birthday: "1967-08-13",
    categories: ["investor"],
    tags: ["asset_management", "finance"],
    nationality: "American",
    title: "CEO of JPMorgan Asset & Wealth Management",
    description:
      "CEO of JPMorgan Asset & Wealth Management overseeing $4.8T, one of the most influential women in finance.",
    imageUrl: null,
    wikidataId: "Q6779766",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mary_Callahan_Erdoes",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Ronald Baron",
    birthday: "1943-06-19",
    categories: ["investor"],
    tags: ["asset_management", "finance"],
    nationality: "American",
    title: "Founder of Baron Capital Group",
    description:
      "Founder of Baron Capital Group, long-term growth investor with $40B+ in AUM across Baron Funds.",
    imageUrl: null,
    wikidataId: "Q16939395",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ron_Baron",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Yasir Al-Rumayyan",
    birthday: "1970-06-01",
    categories: ["investor"],
    tags: ["asset_management", "finance"],
    nationality: "Saudi Arabian",
    title: "Governor of the Public Investment Fund",
    description:
      "Governor of Saudi Arabia's PIF, one of the world's largest sovereign wealth funds with $925B+ in AUM.",
    imageUrl: null,
    wikidataId: "Q28450523",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Yasir_Al-Rumayyan",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Khaldoon Al Mubarak",
    birthday: "1976-01-01",
    categories: ["investor"],
    tags: ["asset_management", "finance"],
    nationality: "Emirati",
    title: "CEO of Mubadala Investment Company",
    description:
      "CEO of Mubadala, Abu Dhabi's $300B sovereign wealth fund investing globally across tech, energy, and healthcare.",
    imageUrl: null,
    wikidataId: "Q6400539",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Khaldoon_Al_Mubarak",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Carlos Slim",
    birthday: "1940-01-28",
    categories: ["investor"],
    tags: ["telecom", "finance"],
    nationality: "Mexican",
    title: "Chairman of Grupo Carso",
    description:
      "Former world's richest person, controls América Móvil, Latin America's largest telecom company.",
    imageUrl: null,
    wikidataId: "Q192582",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Carlos_Slim",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Alwaleed bin Talal",
    birthday: "1955-03-07",
    categories: ["investor"],
    tags: ["finance", "real_estate"],
    nationality: "Saudi Arabian",
    title: "Founder of Kingdom Holding Company",
    description:
      "Saudi prince and investor known as the 'Warren Buffett of Arabia', with stakes in global tech and hospitality.",
    imageUrl: null,
    wikidataId: "Q19289",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Al-Waleed_bin_Talal",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Len Blavatnik",
    birthday: "1957-06-14",
    categories: ["investor"],
    tags: ["private_equity", "media"],
    nationality: "British",
    title: "Founder of Access Industries",
    description:
      "Founder of Access Industries with holdings in Warner Music, chemicals, and tech, major global deal-maker.",
    imageUrl: null,
    wikidataId: "Q438368",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Len_Blavatnik",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Ken Fisher",
    birthday: "1950-11-29",
    categories: ["investor"],
    tags: ["asset_management", "finance"],
    nationality: "American",
    title: "Founder of Fisher Investments",
    description:
      "Founder of Fisher Investments managing $230B+, longest-running Forbes columnist on investing.",
    imageUrl: null,
    wikidataId: "Q6389293",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ken_Fisher",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Chase Coleman",
    birthday: "1975-07-19",
    categories: ["investor"],
    tags: ["hedge_fund", "tech"],
    nationality: "American",
    title: "Founder of Tiger Global Management",
    description:
      "Founder of Tiger Global, one of the most prolific tech investors backing Facebook, LinkedIn, and Spotify early.",
    imageUrl: null,
    wikidataId: "Q5087108",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Chase_Coleman_III",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Jim Rogers",
    birthday: "1942-10-19",
    categories: ["investor"],
    tags: ["finance"],
    nationality: "American",
    title: "Co-founder of Quantum Fund",
    description:
      "Co-founded the Quantum Fund with George Soros, commodity investing legend and global adventurer.",
    imageUrl: null,
    wikidataId: "Q559709",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Jim_Rogers",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Mark Cuban",
    birthday: "1958-07-31",
    categories: ["investor"],
    tags: ["tech", "media"],
    nationality: "American",
    title: "Entrepreneur & Shark Tank Investor",
    description:
      "Owner of Dallas Mavericks and Shark Tank investor who sold Broadcast.com to Yahoo for $5.7B.",
    imageUrl: null,
    wikidataId: "Q318029",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mark_Cuban",
    source: "manual",
    sourceUrl: null,
  },
];
