import type { SeededPerson } from "./index";

import { CENTRAL_BANKERS_EXTRA_SEED } from "./03b-person-banker-extra.seed";

export const CENTRAL_BANKERS_SEED: SeededPerson[] = [
  {
    name: "Jerome Powell",
    birthday: "1953-02-04",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "American",
    title: "Chair of the Federal Reserve",
    description:
      "Chair of the US Federal Reserve since 2018, whose interest rate decisions move global markets instantly.",
    imageUrl: null,
    wikidataId: "Q6179564",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Jerome_Powell",
    popularity: 200,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Christine Lagarde",
    birthday: "1956-01-01",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "French",
    title: "President of the European Central Bank",
    description:
      "President of the ECB since 2019, setting monetary policy for the eurozone's 20 member states.",
    imageUrl: null,
    wikidataId: "Q207523",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Christine_Lagarde",
    popularity: 180,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Kazuo Ueda",
    birthday: "1951-09-20",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Japanese",
    title: "Governor of the Bank of Japan",
    description:
      "Governor of the Bank of Japan since 2023, navigating Japan's exit from decades of ultra-loose monetary policy.",
    imageUrl: null,
    wikidataId: "Q11560952",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kazuo_Ueda",
    popularity: 120,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Andrew Bailey",
    birthday: "1959-06-26",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "British",
    title: "Governor of the Bank of England",
    description:
      "Governor of the Bank of England since 2020, managing UK monetary policy through inflation and uncertainty.",
    imageUrl: null,
    wikidataId: "Q4756939",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Andrew_Bailey_(banker)",
    popularity: 110,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Yi Gang",
    birthday: "1958-03-01",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Chinese",
    title: "Former Governor of the People's Bank of China",
    description:
      "Former PBOC governor who oversaw China's monetary policy and yuan internationalization.",
    imageUrl: null,
    wikidataId: "Q709076",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Yi_Gang",
    popularity: 90,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Kristalina Georgieva",
    birthday: "1953-08-13",
    categories: ["central_banker"],
    tags: ["fiscal_policy", "finance"],
    nationality: "Bulgarian",
    title: "Managing Director of the IMF",
    description:
      "Managing Director of the IMF, overseeing global financial stability and lending to 190 countries.",
    imageUrl: null,
    wikidataId: "Q2362642",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kristalina_Georgieva",
    popularity: 130,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Ajay Banga",
    birthday: "1959-11-10",
    categories: ["central_banker"],
    tags: ["fiscal_policy", "finance"],
    nationality: "American",
    title: "President of the World Bank Group",
    description:
      "President of the World Bank since 2023, directing global development finance and climate funding.",
    imageUrl: null,
    wikidataId: "Q4700171",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ajay_Banga",
    popularity: 100,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Janet Yellen",
    birthday: "1946-08-13",
    categories: ["central_banker"],
    tags: ["monetary_policy", "fiscal_policy", "finance"],
    nationality: "American",
    title: "Former US Treasury Secretary",
    description:
      "Former US Treasury Secretary and Fed Chair, a key architect of US fiscal and monetary policy.",
    imageUrl: null,
    wikidataId: "Q429426",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Janet_Yellen",
    popularity: 170,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Haruhiko Kuroda",
    birthday: "1944-10-25",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Japanese",
    title: "Former Governor of the Bank of Japan",
    description:
      "Former BOJ Governor who pioneered aggressive quantitative easing and negative interest rates.",
    imageUrl: null,
    wikidataId: "Q324422",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Haruhiko_Kuroda",
    popularity: 95,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Mark Carney",
    birthday: "1965-03-16",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "politics"],
    nationality: "Canadian",
    title: "Prime Minister of Canada",
    description:
      "PM of Canada, former Governor of the Bank of England and Bank of Canada, rare finance-to-politics leader.",
    imageUrl: null,
    wikidataId: "Q528536",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mark_Carney",
    popularity: 150,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Pan Gongsheng",
    birthday: "1963-12-01",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Chinese",
    title: "Governor of the People's Bank of China",
    description:
      "Governor of the PBOC since 2023, managing monetary policy for the world's second-largest economy.",
    imageUrl: null,
    wikidataId: "Q15916415",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Pan_Gongsheng",
    popularity: 85,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Shaktikanta Das",
    birthday: "1957-02-26",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Indian",
    title: "Governor of the Reserve Bank of India",
    description:
      "Governor of the RBI, steering monetary policy for the world's fastest-growing major economy.",
    imageUrl: null,
    wikidataId: "Q56283428",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Shaktikanta_Das",
    popularity: 80,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Michele Bullock",
    birthday: "1960-01-15",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Australian",
    title: "Governor of the Reserve Bank of Australia",
    description:
      "First female RBA Governor since 2023, navigating Australia's inflation challenges and housing market.",
    imageUrl: null,
    wikidataId: "Q117039507",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Michele_Bullock",
    popularity: 60,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Elvira Nabiullina",
    birthday: "1963-10-29",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Russian",
    title: "Governor of the Central Bank of Russia",
    description:
      "Governor of the CBR since 2013, managing Russian monetary policy through sanctions and wartime economy.",
    imageUrl: null,
    wikidataId: "Q444039",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Elvira_Nabiullina",
    popularity: 90,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Tiff Macklem",
    birthday: "1961-06-14",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Canadian",
    title: "Governor of the Bank of Canada",
    description:
      "Governor of the Bank of Canada since 2020, managing monetary policy for a major G7 commodity economy.",
    imageUrl: null,
    wikidataId: "Q107133025",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Tiff_Macklem",
    popularity: 65,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Rhee Chang-yong",
    birthday: "1960-05-03",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "South Korean",
    title: "Governor of the Bank of Korea",
    description:
      "Governor of the Bank of Korea since 2022, overseeing monetary policy for a top-10 global economy.",
    imageUrl: null,
    wikidataId: "Q12599283",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Rhee_Chang-yong",
    popularity: 55,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Lesetja Kganyago",
    birthday: "1965-08-10",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "South African",
    title: "Governor of the South African Reserve Bank",
    description:
      "Governor of the SARB since 2014, Africa's most respected central banker managing an emerging economy.",
    imageUrl: null,
    wikidataId: "Q21463770",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lesetja_Kganyago",
    popularity: 50,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Perry Warjiyo",
    birthday: "1959-06-25",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Indonesian",
    title: "Governor of Bank Indonesia",
    description:
      "Governor of Bank Indonesia since 2018, managing monetary policy for Southeast Asia's largest economy.",
    imageUrl: null,
    wikidataId: "Q55627048",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Perry_Warjiyo",
    popularity: 45,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Fatih Karahan",
    birthday: "1982-01-01",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Turkish",
    title: "Governor of the Central Bank of Turkey",
    description:
      "Governor of the TCMB since 2024, restoring orthodox monetary policy after years of unorthodox rates.",
    imageUrl: null,
    wikidataId: null,
    wikipediaUrl: "https://en.wikipedia.org/wiki/Fatih_Karahan",
    popularity: 40,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Victoria Rodríguez Ceja",
    birthday: "1974-10-17",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Mexican",
    title: "Governor of the Bank of Mexico",
    description:
      "First female Banxico Governor since 2022, managing policy for Latin America's second-largest economy.",
    imageUrl: null,
    wikidataId: null,
    wikipediaUrl: "https://en.wikipedia.org/wiki/Victoria_Rodr%C3%ADguez_Ceja",
    popularity: 40,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Sethaput Suthiwartnarueput",
    birthday: "1966-06-23",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Thai",
    title: "Governor of the Bank of Thailand",
    description:
      "Governor of the Bank of Thailand since 2020, steering monetary policy for a key ASEAN economy.",
    imageUrl: null,
    wikidataId: null,
    wikipediaUrl: null,
    popularity: 35,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Joachim Nagel",
    birthday: "1966-10-18",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "German",
    title: "President of the Deutsche Bundesbank",
    description:
      "President of the Bundesbank since 2022 and ECB Governing Council member, influential in eurozone policy.",
    imageUrl: null,
    wikidataId: "Q110220508",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Joachim_Nagel",
    popularity: 50,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "François Villeroy de Galhau",
    birthday: "1959-02-24",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "French",
    title: "Governor of the Banque de France",
    description:
      "Governor of the Banque de France since 2015 and ECB Governing Council member, key eurozone voice.",
    imageUrl: null,
    wikidataId: "Q3085818",
    wikipediaUrl:
      "https://en.wikipedia.org/wiki/Fran%C3%A7ois_Villeroy_de_Galhau",
    popularity: 45,
    source: "manual",
    sourceUrl: null,
  },
  ...CENTRAL_BANKERS_EXTRA_SEED,
];
