import type { SeededPerson } from "./index";

export const CENTRAL_BANKERS_EXTRA_SEED: SeededPerson[] = [
  {
    name: "Fabio Panetta",
    birthday: "1959-08-01",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Italian",
    title: "Governor of the Banca d'Italia",
    description:
      "Governor of the Bank of Italy since 2023, former ECB Executive Board member shaping eurozone policy.",
    imageUrl: null,
    wikidataId: "Q3737529",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Fabio_Panetta",
    popularity: 45,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Luis de Guindos",
    birthday: "1960-01-16",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Spanish",
    title: "Vice President of the ECB",
    description:
      "Vice President of the ECB since 2018, former Spanish Economy Minister, key in eurozone crisis management.",
    imageUrl: null,
    wikidataId: "Q2676460",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Luis_de_Guindos",
    popularity: 40,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Agustín Carstens",
    birthday: "1958-06-09",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Mexican",
    title: "General Manager of the BIS",
    description:
      "General Manager of the Bank for International Settlements, the central bank of central banks.",
    imageUrl: null,
    wikidataId: "Q4372802",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Agust%C3%ADn_Carstens",
    popularity: 70,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Gita Gopinath",
    birthday: "1971-12-08",
    categories: ["central_banker"],
    tags: ["fiscal_policy", "finance"],
    nationality: "American",
    title: "First Deputy Managing Director of the IMF",
    description:
      "First Deputy MD of the IMF, former Chief Economist, one of the most influential economists globally.",
    imageUrl: null,
    wikidataId: "Q56277779",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Gita_Gopinath",
    popularity: 75,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Mario Draghi",
    birthday: "1947-09-03",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "politics"],
    nationality: "Italian",
    title: "Former ECB President & Italian PM",
    description:
      "Former ECB President famous for 'whatever it takes' that saved the euro, later served as Italian PM.",
    imageUrl: null,
    wikidataId: "Q12279",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mario_Draghi",
    popularity: 160,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Ben Bernanke",
    birthday: "1953-12-13",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "American",
    title: "Former Chair of the Federal Reserve",
    description:
      "Former Fed Chair who steered the US through the 2008 financial crisis, Nobel Prize laureate in Economics.",
    imageUrl: null,
    wikidataId: "Q81447",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ben_Bernanke",
    popularity: 150,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Alan Greenspan",
    birthday: "1926-03-06",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "American",
    title: "Former Chair of the Federal Reserve",
    description:
      "Fed Chair for 19 years (1987-2006), his era defined modern central banking and the concept of the 'Greenspan Put'.",
    imageUrl: null,
    wikidataId: "Q22487",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Alan_Greenspan",
    popularity: 140,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Raghuram Rajan",
    birthday: "1963-02-03",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Indian",
    title: "Former Governor of the Reserve Bank of India",
    description:
      "Former RBI Governor and IMF Chief Economist who predicted the 2008 crisis, influential global economist.",
    imageUrl: null,
    wikidataId: "Q3416847",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Raghuram_Rajan",
    popularity: 85,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Zhou Xiaochuan",
    birthday: "1948-01-29",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Chinese",
    title: "Former Governor of the People's Bank of China",
    description:
      "PBOC Governor for 15 years (2002-2018), architect of China's financial modernization and yuan reform.",
    imageUrl: null,
    wikidataId: "Q709597",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Zhou_Xiaochuan",
    popularity: 80,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Mervyn King",
    birthday: "1948-03-30",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "British",
    title: "Former Governor of the Bank of England",
    description:
      "Former BOE Governor (2003-2013) who navigated the UK through the global financial crisis.",
    imageUrl: null,
    wikidataId: "Q333791",
    wikipediaUrl:
      "https://en.wikipedia.org/wiki/Mervyn_King,_Baron_King_of_Lothbury",
    popularity: 70,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Stanley Fischer",
    birthday: "1943-10-15",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "American",
    title: "Former Fed Vice Chair & Bank of Israel Governor",
    description:
      "Former Fed Vice Chair and Bank of Israel Governor, mentor to many of today's top central bankers.",
    imageUrl: null,
    wikidataId: "Q553651",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Stanley_Fischer",
    popularity: 75,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Philip Lane",
    birthday: "1969-08-27",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance"],
    nationality: "Irish",
    title: "Chief Economist of the ECB",
    description:
      "ECB Chief Economist since 2019, key architect of eurozone monetary policy and inflation targeting.",
    imageUrl: null,
    wikidataId: "Q7183890",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Philip_R._Lane",
    popularity: 50,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Isabel Schnabel",
    birthday: "1971-09-09",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance"],
    nationality: "German",
    title: "ECB Executive Board Member",
    description:
      "ECB Executive Board member since 2020, leading voice on climate risks in monetary policy.",
    imageUrl: null,
    wikidataId: "Q15435428",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Isabel_Schnabel",
    popularity: 50,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Lael Brainard",
    birthday: "1962-01-01",
    categories: ["central_banker"],
    tags: ["monetary_policy", "fiscal_policy", "finance"],
    nationality: "American",
    title: "Director of the National Economic Council",
    description:
      "Former Fed Vice Chair, now NEC Director advising the President on economic policy.",
    imageUrl: null,
    wikidataId: "Q6472853",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lael_Brainard",
    popularity: 65,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Neel Kashkari",
    birthday: "1973-07-30",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "American",
    title: "President of the Minneapolis Federal Reserve",
    description:
      "Minneapolis Fed President since 2016, known for hawkish inflation views and TARP oversight during the 2008 crisis.",
    imageUrl: null,
    wikidataId: "Q6986282",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Neel_Kashkari",
    popularity: 55,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "John Williams",
    birthday: "1962-09-12",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "American",
    title: "President of the New York Federal Reserve",
    description:
      "President of the NY Fed since 2018, permanent FOMC voting member with outsized influence on US rates.",
    imageUrl: null,
    wikidataId: "Q56282889",
    wikipediaUrl: "https://en.wikipedia.org/wiki/John_C._Williams_(economist)",
    popularity: 60,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Thomas Jordan",
    birthday: "1963-04-15",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Swiss",
    title: "Former Chairman of the Swiss National Bank",
    description:
      "Former SNB Chairman (2012-2024), managed the Swiss franc floor against the euro and negative rates.",
    imageUrl: null,
    wikidataId: "Q20648637",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Thomas_J._Jordan",
    popularity: 55,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Masaaki Shirakawa",
    birthday: "1949-09-27",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Japanese",
    title: "Former Governor of the Bank of Japan",
    description:
      "Former BOJ Governor (2008-2013), navigated Japan through the global financial crisis and Fukushima disaster.",
    imageUrl: null,
    wikidataId: "Q741497",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Masaaki_Shirakawa",
    popularity: 45,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Gabriel Galípolo",
    birthday: "1982-07-09",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "Brazilian",
    title: "Governor of the Central Bank of Brazil",
    description:
      "Governor of BCB since 2025, steering monetary policy for Latin America's largest economy.",
    imageUrl: null,
    wikidataId: null,
    wikipediaUrl: "https://en.wikipedia.org/wiki/Gabriel_Gal%C3%ADpolo",
    popularity: 40,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Adrian Orr",
    birthday: "1964-12-12",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "New Zealander",
    title: "Governor of the Reserve Bank of New Zealand",
    description:
      "RBNZ Governor since 2018, pioneer of dual mandate including employment alongside price stability.",
    imageUrl: null,
    wikidataId: "Q56283197",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Adrian_Orr",
    popularity: 40,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Claudia Buch",
    birthday: "1966-06-03",
    categories: ["central_banker"],
    tags: ["monetary_policy", "finance", "banking"],
    nationality: "German",
    title: "Chair of the ECB Supervisory Board",
    description:
      "Chair of ECB Banking Supervision since 2024, overseeing stability of the eurozone's largest banks.",
    imageUrl: null,
    wikidataId: "Q1094709",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Claudia_Buch",
    popularity: 35,
    source: "manual",
    sourceUrl: null,
  },
];
