import type { SeededPerson } from "./index";

export const ENTREPRENEURS_SEED: SeededPerson[] = [
  {
    name: "Bernard Arnault",
    birthday: "1949-03-05",
    categories: ["entrepreneur"],
    tags: ["luxury", "manufacturing"],
    nationality: "French",
    title: "Chairman & CEO of LVMH",
    description:
      "Chairman of LVMH, the world's largest luxury goods conglomerate and one of the wealthiest people.",
    imageUrl: null,
    wikidataId: "Q313556",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Bernard_Arnault",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Tim Cook",
    birthday: "1960-11-01",
    categories: ["entrepreneur"],
    tags: ["tech", "manufacturing", "semiconductor"],
    nationality: "American",
    title: "CEO of Apple",
    description:
      "CEO of Apple, the world's most valuable company, driving global supply chains and consumer technology.",
    imageUrl: null,
    wikidataId: "Q265073",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Tim_Cook",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Satya Nadella",
    birthday: "1967-08-19",
    categories: ["entrepreneur"],
    tags: ["tech", "cloud", "ai"],
    nationality: "American",
    title: "CEO of Microsoft",
    description:
      "CEO of Microsoft, leading the AI revolution with OpenAI partnership and Azure cloud dominance.",
    imageUrl: null,
    wikidataId: "Q528534",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Satya_Nadella",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Larry Fink",
    birthday: "1952-11-02",
    categories: ["entrepreneur"],
    tags: ["finance", "asset_management"],
    nationality: "American",
    title: "CEO of BlackRock",
    description:
      "CEO of BlackRock, the world's largest asset manager with over $10 trillion AUM.",
    imageUrl: null,
    wikidataId: "Q1373478",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Larry_Fink",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Jamie Dimon",
    birthday: "1956-03-13",
    categories: ["entrepreneur"],
    tags: ["finance", "banking"],
    nationality: "American",
    title: "CEO of JPMorgan Chase",
    description:
      "CEO of JPMorgan Chase, the largest US bank, whose outlook shapes global financial sentiment.",
    imageUrl: null,
    wikidataId: "Q1371592",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Jamie_Dimon",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Sundar Pichai",
    birthday: "1972-06-10",
    categories: ["entrepreneur"],
    tags: ["tech", "ai", "cloud", "media"],
    nationality: "American",
    title: "CEO of Alphabet (Google)",
    description:
      "CEO of Alphabet/Google, leading the world's dominant search engine, AI research, and ads platform.",
    imageUrl: null,
    wikidataId: "Q22079550",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Sundar_Pichai",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Vitalik Buterin",
    birthday: "1994-01-31",
    categories: ["entrepreneur"],
    tags: ["crypto", "blockchain", "defi"],
    nationality: "Canadian",
    title: "Co-founder of Ethereum",
    description:
      "Co-founder of Ethereum, the blockchain platform powering DeFi, NFTs, and smart contracts.",
    imageUrl: null,
    wikidataId: "Q20895970",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Vitalik_Buterin",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Brian Armstrong",
    birthday: "1983-01-25",
    categories: ["entrepreneur"],
    tags: ["crypto", "blockchain", "finance"],
    nationality: "American",
    title: "CEO of Coinbase",
    description:
      "CEO of Coinbase, the largest US crypto exchange and first major crypto company listed on NASDAQ.",
    imageUrl: null,
    wikidataId: "Q47302029",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Brian_Armstrong_(businessman)",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Michael Saylor",
    birthday: "1965-02-04",
    categories: ["entrepreneur"],
    tags: ["crypto", "blockchain", "tech"],
    nationality: "American",
    title: "Executive Chairman of MicroStrategy",
    description:
      "Executive Chairman of MicroStrategy, the largest corporate holder of Bitcoin.",
    imageUrl: null,
    wikidataId: "Q3856753",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Michael_Saylor",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Sam Bankman-Fried",
    birthday: "1992-03-06",
    categories: ["entrepreneur"],
    tags: ["crypto", "blockchain", "finance"],
    nationality: "American",
    title: "Former CEO of FTX",
    description:
      "Founder of FTX, whose collapse was one of the largest financial frauds, reshaping crypto regulation.",
    imageUrl: null,
    wikidataId: "Q107596730",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Sam_Bankman-Fried",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Anatoly Yakovenko",
    birthday: "1982-09-22",
    categories: ["entrepreneur"],
    tags: ["crypto", "blockchain", "tech"],
    nationality: "American",
    title: "Co-founder of Solana",
    description:
      "Co-founder of Solana Labs, the high-performance blockchain challenging Ethereum.",
    imageUrl: null,
    wikidataId: "Q107596731",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Anatoly_Yakovenko",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Jack Ma",
    birthday: "1964-09-10",
    categories: ["entrepreneur"],
    tags: ["tech", "ecommerce"],
    nationality: "Chinese",
    title: "Co-founder of Alibaba Group",
    description:
      "Co-founder of Alibaba, China's largest e-commerce platform and fintech ecosystem through Ant Group.",
    imageUrl: null,
    wikidataId: "Q16349",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Jack_Ma",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Sam Altman",
    birthday: "1985-04-22",
    categories: ["entrepreneur"],
    tags: ["tech", "ai"],
    nationality: "American",
    title: "CEO of OpenAI",
    description:
      "CEO of OpenAI, the company behind ChatGPT that ignited the global AI race and reshaped the tech industry.",
    imageUrl: null,
    wikidataId: "Q2769434",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Sam_Altman",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Patrick Collison",
    birthday: "1988-09-09",
    categories: ["entrepreneur"],
    tags: ["tech", "finance"],
    nationality: "Irish",
    title: "CEO of Stripe",
    description:
      "Co-founder and CEO of Stripe, processing hundreds of billions in payments for internet businesses globally.",
    imageUrl: null,
    wikidataId: "Q15063490",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Patrick_Collison",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Evan Spiegel",
    birthday: "1990-06-04",
    categories: ["entrepreneur"],
    tags: ["tech", "social_media"],
    nationality: "American",
    title: "CEO of Snap Inc.",
    description:
      "Co-founder and CEO of Snap Inc. (Snapchat), pioneering ephemeral messaging and AR experiences.",
    imageUrl: null,
    wikidataId: "Q17154085",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Evan_Spiegel",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Reed Hastings",
    birthday: "1960-10-08",
    categories: ["entrepreneur"],
    tags: ["tech", "media"],
    nationality: "American",
    title: "Co-founder of Netflix",
    description:
      "Co-founder of Netflix who revolutionized entertainment, transforming how billions consume media worldwide.",
    imageUrl: null,
    wikidataId: "Q959007",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Reed_Hastings",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Brian Chesky",
    birthday: "1981-08-29",
    categories: ["entrepreneur"],
    tags: ["tech", "ecommerce"],
    nationality: "American",
    title: "CEO of Airbnb",
    description:
      "Co-founder and CEO of Airbnb, disrupting the global hospitality industry with the sharing economy model.",
    imageUrl: null,
    wikidataId: "Q18425694",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Brian_Chesky",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Daniel Ek",
    birthday: "1983-02-21",
    categories: ["entrepreneur"],
    tags: ["tech", "media"],
    nationality: "Swedish",
    title: "CEO of Spotify",
    description:
      "Co-founder and CEO of Spotify, the world's largest audio streaming platform with 600M+ users.",
    imageUrl: null,
    wikidataId: "Q17125728",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Daniel_Ek",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Lei Jun",
    birthday: "1969-12-16",
    categories: ["entrepreneur"],
    tags: ["tech", "manufacturing"],
    nationality: "Chinese",
    title: "CEO of Xiaomi",
    description:
      "Founder and CEO of Xiaomi, driving affordable smartphones and smart home tech globally, now entering EVs.",
    imageUrl: null,
    wikidataId: "Q1397987",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lei_Jun",
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Robin Li",
    birthday: "1968-11-17",
    categories: ["entrepreneur"],
    tags: ["tech", "ai"],
    nationality: "Chinese",
    title: "CEO of Baidu",
    description:
      "Co-founder and CEO of Baidu, China's largest search engine, now pivoting heavily into AI and autonomous driving.",
    imageUrl: null,
    wikidataId: "Q1389867",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Robin_Li",
    source: "manual",
    sourceUrl: null,
  },
];
