import type { SeededPerson } from "./index";

export const INFLUENCERS_SEED: SeededPerson[] = [
  {
    name: "Cristiano Ronaldo",
    birthday: "1985-02-05",
    categories: ["influencer"],
    tags: ["social_media"],
    nationality: "Portuguese",
    title: "Football Icon & Most-Followed Person",
    description:
      "Most-followed person on Instagram with 600M+ followers, global football icon whose endorsements move billion-dollar markets.",
    imageUrl: null,
    wikidataId: "Q11571",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Cristiano_Ronaldo",
    popularity: 200,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Lionel Messi",
    birthday: "1987-06-24",
    categories: ["influencer"],
    tags: ["social_media"],
    nationality: "Argentine",
    title: "Football Legend & Global Brand Ambassador",
    description:
      "Eight-time Ballon d'Or winner with 500M+ social media followers, driving massive brand valuations globally.",
    imageUrl: null,
    wikidataId: "Q615",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lionel_Messi",
    popularity: 195,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "MrBeast",
    birthday: "1998-05-07",
    categories: ["influencer"],
    tags: ["social_media", "ecommerce"],
    nationality: "American",
    title: "YouTube Creator & Entrepreneur",
    description:
      "Most-subscribed individual YouTuber with 300M+ subscribers, built a billion-dollar media and consumer brand empire.",
    imageUrl: null,
    wikidataId: "Q109321867",
    wikipediaUrl: "https://en.wikipedia.org/wiki/MrBeast",
    popularity: 180,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Kylie Jenner",
    birthday: "1997-08-10",
    categories: ["influencer"],
    tags: ["social_media", "luxury"],
    nationality: "American",
    title: "Media Personality & Kylie Cosmetics Founder",
    description:
      "Social media mogul and founder of Kylie Cosmetics, one of the youngest self-made billionaires leveraging social influence.",
    imageUrl: null,
    wikidataId: "Q4622823",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kylie_Jenner",
    popularity: 170,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Kim Kardashian",
    birthday: "1980-10-21",
    categories: ["influencer"],
    tags: ["social_media", "luxury"],
    nationality: "American",
    title: "Media Mogul & SKIMS Founder",
    description:
      "Reality TV pioneer turned billionaire entrepreneur with SKIMS and KKW Beauty, 400M+ social media followers.",
    imageUrl: null,
    wikidataId: "Q186327",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kim_Kardashian",
    popularity: 165,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Selena Gomez",
    birthday: "1992-07-22",
    categories: ["influencer"],
    tags: ["social_media", "media"],
    nationality: "American",
    title: "Singer, Actress & Rare Beauty Founder",
    description:
      "Top-followed woman on Instagram, singer-actress and founder of Rare Beauty, a billion-dollar cosmetics brand.",
    imageUrl: null,
    wikidataId: "Q83287",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Selena_Gomez",
    popularity: 160,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Dwayne Johnson",
    birthday: "1972-05-02",
    categories: ["influencer"],
    tags: ["social_media", "media"],
    nationality: "American",
    title: "Actor & Entrepreneur",
    description:
      "Highest-paid actor and one of the most-followed people on social media, with major brand partnerships and business ventures.",
    imageUrl: null,
    wikidataId: "Q189600",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Dwayne_Johnson",
    popularity: 155,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Taylor Swift",
    birthday: "1989-12-13",
    categories: ["influencer"],
    tags: ["social_media", "media"],
    nationality: "American",
    title: "Singer-Songwriter & Billionaire Artist",
    description:
      "First musician to become a billionaire solely from music, her album releases and tours measurably impact GDP of host cities.",
    imageUrl: null,
    wikidataId: "Q26876",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Taylor_Swift",
    popularity: 185,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Beyoncé",
    birthday: "1981-09-04",
    categories: ["influencer"],
    tags: ["social_media", "media"],
    nationality: "American",
    title: "Singer & Cultural Icon",
    description:
      "Global music icon with massive cultural and economic influence, her tours and brand deals generate billions in economic activity.",
    imageUrl: null,
    wikidataId: "Q36153",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Beyonc%C3%A9",
    popularity: 150,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Virat Kohli",
    birthday: "1988-11-05",
    categories: ["influencer"],
    tags: ["social_media"],
    nationality: "Indian",
    title: "Cricket Icon & Brand Powerhouse",
    description:
      "India's most-followed athlete with 270M+ Instagram followers, the most valuable celebrity brand in Indian sports.",
    imageUrl: null,
    wikidataId: "Q213854",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Virat_Kohli",
    popularity: 145,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Neymar Jr",
    birthday: "1992-02-05",
    categories: ["influencer"],
    tags: ["social_media"],
    nationality: "Brazilian",
    title: "Football Star & Global Brand",
    description:
      "One of the world's highest-earning athletes with 200M+ Instagram followers and massive global endorsement portfolio.",
    imageUrl: null,
    wikidataId: "Q178443",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Neymar",
    popularity: 140,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Khaby Lame",
    birthday: "2000-03-09",
    categories: ["influencer"],
    tags: ["social_media"],
    nationality: "Italian",
    title: "Most-Followed TikTok Creator",
    description:
      "Most-followed person on TikTok with 160M+ followers, turned viral comedy into a global media brand.",
    imageUrl: null,
    wikidataId: "Q107412517",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Khaby_Lame",
    popularity: 130,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "PewDiePie",
    birthday: "1989-10-24",
    categories: ["influencer"],
    tags: ["social_media", "media"],
    nationality: "Swedish",
    title: "YouTube Pioneer",
    description:
      "YouTube pioneer Felix Kjellberg who shaped the creator economy, formerly the platform's most-subscribed individual.",
    imageUrl: null,
    wikidataId: "Q15080743",
    wikipediaUrl: "https://en.wikipedia.org/wiki/PewDiePie",
    popularity: 125,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Oprah Winfrey",
    birthday: "1954-01-29",
    categories: ["influencer"],
    tags: ["social_media", "media"],
    nationality: "American",
    title: "Media Mogul & Philanthropist",
    description:
      "Billionaire media mogul whose endorsements and opinions move markets, from book sales to political campaigns.",
    imageUrl: null,
    wikidataId: "Q55800",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Oprah_Winfrey",
    popularity: 175,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Rihanna",
    birthday: "1988-02-20",
    categories: ["influencer"],
    tags: ["social_media", "luxury"],
    nationality: "Barbadian",
    title: "Singer & Fenty Empire Founder",
    description:
      "Billionaire singer-entrepreneur who built Fenty Beauty and Savage X Fenty into multi-billion-dollar global brands.",
    imageUrl: null,
    wikidataId: "Q36844",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Rihanna",
    popularity: 160,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "LeBron James",
    birthday: "1984-12-30",
    categories: ["influencer"],
    tags: ["social_media"],
    nationality: "American",
    title: "Basketball Icon & Media Mogul",
    description:
      "First active NBA player to become a billionaire, with SpringHill media company and massive investment portfolio.",
    imageUrl: null,
    wikidataId: "Q36159",
    wikipediaUrl: "https://en.wikipedia.org/wiki/LeBron_James",
    popularity: 165,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Kylian Mbappé",
    birthday: "1998-12-20",
    categories: ["influencer"],
    tags: ["social_media"],
    nationality: "French",
    title: "Football Star & Global Ambassador",
    description:
      "World's most valuable footballer with 100M+ social media followers, one of the highest-paid athletes globally.",
    imageUrl: null,
    wikidataId: "Q22924312",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kylian_Mbapp%C3%A9",
    popularity: 135,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Shakira",
    birthday: "1977-02-02",
    categories: ["influencer"],
    tags: ["social_media", "media"],
    nationality: "Colombian",
    title: "Global Music Icon",
    description:
      "Colombian singer with 90M+ Instagram followers whose music and brand partnerships reach billions worldwide.",
    imageUrl: null,
    wikidataId: "Q34424",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Shakira",
    popularity: 120,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Ariana Grande",
    birthday: "1993-06-26",
    categories: ["influencer"],
    tags: ["social_media", "media"],
    nationality: "American",
    title: "Pop Star & Brand Icon",
    description:
      "Pop superstar with 380M+ Instagram followers, her fragrance line alone has generated over $1B in revenue.",
    imageUrl: null,
    wikidataId: "Q151917",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ariana_Grande",
    popularity: 155,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Justin Bieber",
    birthday: "1994-03-01",
    categories: ["influencer"],
    tags: ["social_media", "media"],
    nationality: "Canadian",
    title: "Pop Star & Cultural Trendsetter",
    description:
      "Global pop icon who pioneered social-media-driven music careers, with 300M+ followers across platforms.",
    imageUrl: null,
    wikidataId: "Q34086",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Justin_Bieber",
    popularity: 145,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Gordon Ramsay",
    birthday: "1966-11-08",
    categories: ["influencer"],
    tags: ["social_media", "media"],
    nationality: "British",
    title: "Celebrity Chef & Media Empire",
    description:
      "Michelin-starred chef turned global media brand with 90M+ social followers and a restaurant empire spanning continents.",
    imageUrl: null,
    wikidataId: "Q189643",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Gordon_Ramsay",
    popularity: 115,
    source: "manual",
    sourceUrl: null,
  },
  {
    name: "Charli D'Amelio",
    birthday: "2004-05-01",
    categories: ["influencer"],
    tags: ["social_media"],
    nationality: "American",
    title: "TikTok Pioneer & Gen-Z Icon",
    description:
      "First TikTok creator to reach 100M followers, pioneering Gen-Z creator economy and brand partnerships.",
    imageUrl: null,
    wikidataId: "Q71413446",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Charli_D%27Amelio",
    popularity: 110,
    source: "manual",
    sourceUrl: null,
  },
];
