import type { SeededPerson } from "./index";

/**
 * Active presidents & heads of state (G20 + key economies) as of 2026.
 * These are the leaders whose decisions directly impact the world economy.
 */
export const ACTIVE_PRESIDENTS: SeededPerson[] = [
  {
    name: "Donald Trump",
    birthday: "1946-06-14",
    categories: ["world_leader"],
    nationality: "American",
    title: "President of the United States",
    description:
      "47th President of the United States, businessman and media personality who returned to office in 2025.",
    imageUrl: null,
    wikidataId: "Q22686",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Donald_Trump",
    source: "manual",
    sourceUrl: "https://en.wikipedia.org/wiki/Donald_Trump",
  },
  {
    name: "Xi Jinping",
    birthday: "1953-06-15",
    categories: ["world_leader"],
    nationality: "Chinese",
    title: "President of China",
    description:
      "General Secretary of the CPC and President of the People's Republic of China since 2013, leading the world's second-largest economy.",
    imageUrl: null,
    wikidataId: "Q15031",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Xi_Jinping",
    source: "manual",
    sourceUrl: "https://en.wikipedia.org/wiki/Xi_Jinping",
  },
  {
    name: "Vladimir Putin",
    birthday: "1952-10-07",
    categories: ["world_leader"],
    nationality: "Russian",
    title: "President of Russia",
    description:
      "President of Russia, leading one of the world's largest energy exporters and a key geopolitical player impacting global markets.",
    imageUrl: null,
    wikidataId: "Q7747",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Vladimir_Putin",
    source: "manual",
    sourceUrl: "https://en.wikipedia.org/wiki/Vladimir_Putin",
  },
  {
    name: "Narendra Modi",
    birthday: "1950-09-17",
    categories: ["world_leader"],
    nationality: "Indian",
    title: "Prime Minister of India",
    description:
      "Prime Minister of India since 2014, overseeing the world's fastest-growing major economy and digital transformation.",
    imageUrl: null,
    wikidataId: "Q1058",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Narendra_Modi",
    source: "manual",
    sourceUrl: "https://en.wikipedia.org/wiki/Narendra_Modi",
  },
  {
    name: "Keir Starmer",
    birthday: "1962-09-02",
    categories: ["world_leader"],
    nationality: "British",
    title: "Prime Minister of the United Kingdom",
    description:
      "Prime Minister of the UK since 2024, leading the world's sixth-largest economy and a major global financial center.",
    imageUrl: null,
    wikidataId: "Q6387023",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Keir_Starmer",
    source: "manual",
    sourceUrl: "https://en.wikipedia.org/wiki/Keir_Starmer",
  },
  {
    name: "Emmanuel Macron",
    birthday: "1977-12-21",
    categories: ["world_leader"],
    nationality: "French",
    title: "President of France",
    description:
      "President of France since 2017, former investment banker leading the EU's second-largest economy.",
    imageUrl: null,
    wikidataId: "Q3052772",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Emmanuel_Macron",
    source: "manual",
    sourceUrl: "https://en.wikipedia.org/wiki/Emmanuel_Macron",
  },
  {
    name: "Olaf Scholz",
    birthday: "1958-06-14",
    categories: ["world_leader"],
    nationality: "German",
    title: "Chancellor of Germany",
    description:
      "Chancellor of Germany since 2021, leading the EU's largest economy and a global manufacturing powerhouse.",
    imageUrl: null,
    wikidataId: "Q61053",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Olaf_Scholz",
    source: "manual",
    sourceUrl: "https://en.wikipedia.org/wiki/Olaf_Scholz",
  },
  {
    name: "Shigeru Ishiba",
    birthday: "1957-02-04",
    categories: ["world_leader"],
    nationality: "Japanese",
    title: "Prime Minister of Japan",
    description:
      "Prime Minister of Japan since 2024, leading the world's fourth-largest economy.",
    imageUrl: null,
    wikidataId: "Q311453",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Shigeru_Ishiba",
    source: "manual",
    sourceUrl: "https://en.wikipedia.org/wiki/Shigeru_Ishiba",
  },
  {
    name: "Luiz Inácio Lula da Silva",
    birthday: "1945-10-27",
    categories: ["world_leader"],
    nationality: "Brazilian",
    title: "President of Brazil",
    description:
      "President of Brazil serving his third term since 2023, leading Latin America's largest economy and a major commodity exporter.",
    imageUrl: null,
    wikidataId: "Q37181",
    wikipediaUrl:
      "https://en.wikipedia.org/wiki/Luiz_In%C3%A1cio_Lula_da_Silva",
    source: "manual",
    sourceUrl: "https://en.wikipedia.org/wiki/Luiz_In%C3%A1cio_Lula_da_Silva",
  },
  {
    name: "Mohammed bin Salman",
    birthday: "1985-08-31",
    categories: ["world_leader"],
    tags: ["energy", "oil_gas", "politics"],
    nationality: "Saudi Arabian",
    title: "Crown Prince of Saudi Arabia",
    description:
      "Crown Prince and Prime Minister of Saudi Arabia, de facto leader of the world's largest oil exporter and OPEC's most influential member.",
    imageUrl: null,
    wikidataId: "Q6888847",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mohammed_bin_Salman",
    source: "manual",
    sourceUrl: "https://en.wikipedia.org/wiki/Mohammed_bin_Salman",
  },
  {
    name: "Volodymyr Zelenskyy",
    birthday: "1978-01-25",
    categories: ["world_leader"],
    nationality: "Ukrainian",
    title: "President of Ukraine",
    description:
      "President of Ukraine since 2019, leading the country through the Russia-Ukraine war with massive global economic implications.",
    imageUrl: null,
    wikidataId: "Q2656481",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Volodymyr_Zelenskyy",
    source: "manual",
    sourceUrl: "https://en.wikipedia.org/wiki/Volodymyr_Zelenskyy",
  },
];
