/* eslint-disable max-lines */
/**
 * Translations for database terms that appear in AI responses.
 * These Balinese/English terms from database.ts need to be rendered
 * in the user's language when the AI mentions them.
 */
export const TERM_TRANSLATIONS: Record<string, Record<string, string>> = {
  // lahir_untuk / diberi_hak_untuk names
  GURU: {
    id: "GURU",
    de: "GURU",
    es: "GURU",
    fr: "GURU",
    ja: "グル",
    ko: "구루",
    pt: "GURU",
    ru: "ГУРУ",
    zh: "导师",
  },
  RATU: {
    id: "RATU",
    de: "RATU",
    es: "RATU",
    fr: "RATU",
    ja: "ラトゥ",
    ko: "라투",
    pt: "RATU",
    ru: "РАТУ",
    zh: "守护者",
  },
  LARA: {
    id: "LARA",
    de: "LARA",
    es: "LARA",
    fr: "LARA",
    ja: "ララ",
    ko: "라라",
    pt: "LARA",
    ru: "ЛАРА",
    zh: "成长",
  },
  PATI: {
    id: "PATI",
    de: "PATI",
    es: "PATI",
    fr: "PATI",
    ja: "パティ",
    ko: "파티",
    pt: "PATI",
    ru: "ПАТИ",
    zh: "解脱",
  },
  // lahir_untuk descriptions
  GUIDING: {
    id: "MEMBIMBING",
    de: "FÜHREND",
    es: "GUIANDO",
    fr: "GUIDANT",
    ja: "導く",
    ko: "안내",
    pt: "GUIANDO",
    ru: "НАПРАВЛЯЮЩИЙ",
    zh: "引导",
  },
  PROTECTING: {
    id: "MELINDUNGI",
    de: "SCHÜTZEND",
    es: "PROTEGIENDO",
    fr: "PROTÉGEANT",
    ja: "守る",
    ko: "보호",
    pt: "PROTEGENDO",
    ru: "ЗАЩИЩАЮЩИЙ",
    zh: "保护",
  },
  GROWING: {
    id: "BERTUMBUH",
    de: "WACHSEND",
    es: "CRECIENDO",
    fr: "GRANDISSANT",
    ja: "成長する",
    ko: "성장",
    pt: "CRESCENDO",
    ru: "РАСТУЩИЙ",
    zh: "成长",
  },
  RELEASING: {
    id: "MELEPASKAN",
    de: "LOSLASSEND",
    es: "LIBERANDO",
    fr: "LIBÉRANT",
    ja: "解放する",
    ko: "해방",
    pt: "LIBERANDO",
    ru: "ОСВОБОЖДАЮЩИЙ",
    zh: "释放",
  },
  // tindakan (actions)
  MINDFULNESS: {
    id: "KESADARAN",
    de: "ACHTSAMKEIT",
    es: "ATENCIÓN PLENA",
    fr: "PLEINE CONSCIENCE",
    ja: "マインドフルネス",
    ko: "마음챙김",
    pt: "ATENÇÃO PLENA",
    ru: "ОСОЗНАННОСТЬ",
    zh: "正念",
  },
  WORSHIP: {
    id: "IBADAH",
    de: "ANDACHT",
    es: "DEVOCIÓN",
    fr: "DÉVOTION",
    ja: "礼拝",
    ko: "예배",
    pt: "DEVOÇÃO",
    ru: "ПОКЛОНЕНИЕ",
    zh: "祈祷",
  },
  PROBIOTIC: {
    id: "PROBIOTIK",
    de: "PROBIOTISCH",
    es: "PROBIÓTICO",
    fr: "PROBIOTIQUE",
    ja: "プロバイオティクス",
    ko: "프로바이오틱",
    pt: "PROBIÓTICO",
    ru: "ПРОБИОТИК",
    zh: "益生菌",
  },
  SERVICE: {
    id: "PELAYANAN",
    de: "DIENST",
    es: "SERVICIO",
    fr: "SERVICE",
    ja: "奉仕",
    ko: "봉사",
    pt: "SERVIÇO",
    ru: "СЛУЖЕНИЕ",
    zh: "服务",
  },
  "CLEAN UP": {
    id: "BERSIH-BERSIH",
    de: "AUFRÄUMEN",
    es: "LIMPIAR",
    fr: "NETTOYAGE",
    ja: "浄化",
    ko: "정화",
    pt: "LIMPEZA",
    ru: "ОЧИЩЕНИЕ",
    zh: "清理",
  },
  "DEEP SLEEP": {
    id: "TIDUR NYENYAK",
    de: "TIEFSCHLAF",
    es: "SUEÑO PROFUNDO",
    fr: "SOMMEIL PROFOND",
    ja: "深い眠り",
    ko: "깊은 수면",
    pt: "SONO PROFUNDO",
    ru: "ГЛУБОКИЙ СОН",
    zh: "深度睡眠",
  },
  // cipta (psychosocial)
  TRUST: {
    id: "KEPERCAYAAN",
    de: "VERTRAUEN",
    es: "CONFIANZA",
    fr: "CONFIANCE",
    ja: "信頼",
    ko: "신뢰",
    pt: "CONFIANÇA",
    ru: "ДОВЕРИЕ",
    zh: "信任",
  },
  AUTONOMY: {
    id: "OTONOMI",
    de: "AUTONOMIE",
    es: "AUTONOMÍA",
    fr: "AUTONOMIE",
    ja: "自律",
    ko: "자율성",
    pt: "AUTONOMIA",
    ru: "АВТОНОМИЯ",
    zh: "自主",
  },
  INITIATIVE: {
    id: "INISIATIF",
    de: "INITIATIVE",
    es: "INICIATIVA",
    fr: "INITIATIVE",
    ja: "主導権",
    ko: "주도성",
    pt: "INICIATIVA",
    ru: "ИНИЦИАТИВА",
    zh: "主动",
  },
  DILIGENT: {
    id: "RAJIN",
    de: "FLEISSIG",
    es: "DILIGENTE",
    fr: "DILIGENT",
    ja: "勤勉",
    ko: "근면",
    pt: "DILIGENTE",
    ru: "УСЕРДИЕ",
    zh: "勤奋",
  },
  IDENTITY: {
    id: "IDENTITAS",
    de: "IDENTITÄT",
    es: "IDENTIDAD",
    fr: "IDENTITÉ",
    ja: "アイデンティティ",
    ko: "정체성",
    pt: "IDENTIDADE",
    ru: "ИДЕНТИЧНОСТЬ",
    zh: "认同",
  },
  INTIMATE: {
    id: "KEINTIMAN",
    de: "INTIMITÄT",
    es: "INTIMIDAD",
    fr: "INTIMITÉ",
    ja: "親密",
    ko: "친밀",
    pt: "INTIMIDADE",
    ru: "БЛИЗОСТЬ",
    zh: "亲密",
  },
  DYNAMIC: {
    id: "DINAMIS",
    de: "DYNAMISCH",
    es: "DINÁMICO",
    fr: "DYNAMIQUE",
    ja: "ダイナミック",
    ko: "역동적",
    pt: "DINÂMICO",
    ru: "ДИНАМИКА",
    zh: "活力",
  },
  INTEGRITY: {
    id: "INTEGRITAS",
    de: "INTEGRITÄT",
    es: "INTEGRIDAD",
    fr: "INTÉGRITÉ",
    ja: "誠実",
    ko: "성실",
    pt: "INTEGRIDADE",
    ru: "ЧЕСТНОСТЬ",
    zh: "正直",
  },
  // rasa (emotional)
  PEACE: {
    id: "DAMAI",
    de: "FRIEDEN",
    es: "PAZ",
    fr: "PAIX",
    ja: "平和",
    ko: "평화",
    pt: "PAZ",
    ru: "ПОКОЙ",
    zh: "平和",
  },
  APATHY: {
    id: "APATIS",
    de: "APATHIE",
    es: "APATÍA",
    fr: "APATHIE",
    ja: "無感動",
    ko: "무관심",
    pt: "APATIA",
    ru: "АПАТИЯ",
    zh: "冷漠",
  },
  ANGER: {
    id: "MARAH",
    de: "WUT",
    es: "IRA",
    fr: "COLÈRE",
    ja: "怒り",
    ko: "분노",
    pt: "RAIVA",
    ru: "ГНЕВ",
    zh: "愤怒",
  },
  GRIEF: {
    id: "DUKA",
    de: "TRAUER",
    es: "DOLOR",
    fr: "CHAGRIN",
    ja: "悲嘆",
    ko: "슬픔",
    pt: "LUTO",
    ru: "ГОРЕ",
    zh: "悲伤",
  },
  PRIDE: {
    id: "BANGGA",
    de: "STOLZ",
    es: "ORGULLO",
    fr: "FIERTÉ",
    ja: "誇り",
    ko: "자부심",
    pt: "ORGULHO",
    ru: "ГОРДОСТЬ",
    zh: "自豪",
  },
  PASSION: {
    id: "GAIRAH",
    de: "LEIDENSCHAFT",
    es: "PASIÓN",
    fr: "PASSION",
    ja: "情熱",
    ko: "열정",
    pt: "PAIXÃO",
    ru: "СТРАСТЬ",
    zh: "热情",
  },
  FEAR: {
    id: "TAKUT",
    de: "ANGST",
    es: "MIEDO",
    fr: "PEUR",
    ja: "恐れ",
    ko: "두려움",
    pt: "MEDO",
    ru: "СТРАХ",
    zh: "恐惧",
  },
  FIRM: {
    id: "TEGUH",
    de: "FEST",
    es: "FIRME",
    fr: "FERME",
    ja: "堅固",
    ko: "확고",
    pt: "FIRME",
    ru: "СТОЙКОСТЬ",
    zh: "坚定",
  },
  SINCERE: {
    id: "TULUS",
    de: "AUFRICHTIG",
    es: "SINCERO",
    fr: "SINCÈRE",
    ja: "誠実",
    ko: "진심",
    pt: "SINCERO",
    ru: "ИСКРЕННОСТЬ",
    zh: "真诚",
  },
  // karsa (behavioral)
  LISTENING: {
    id: "MENDENGARKAN",
    de: "ZUHÖREN",
    es: "ESCUCHAR",
    fr: "ÉCOUTER",
    ja: "傾聴",
    ko: "경청",
    pt: "OUVIR",
    ru: "СЛУШАНИЕ",
    zh: "倾听",
  },
  SHARING: {
    id: "BERBAGI",
    de: "TEILEN",
    es: "COMPARTIR",
    fr: "PARTAGER",
    ja: "共有",
    ko: "나눔",
    pt: "COMPARTILHAR",
    ru: "ДЕЛИТЬСЯ",
    zh: "分享",
  },
  EMPATHY: {
    id: "EMPATI",
    de: "EMPATHIE",
    es: "EMPATÍA",
    fr: "EMPATHIE",
    ja: "共感",
    ko: "공감",
    pt: "EMPATIA",
    ru: "ЭМПАТИЯ",
    zh: "共情",
  },
  "GESTURE(+)": {
    id: "GESTUR POSITIF",
    de: "POSITIVE GESTE",
    es: "GESTO POSITIVO",
    fr: "GESTE POSITIF",
    ja: "ポジティブジェスチャー",
    ko: "긍정적 제스처",
    pt: "GESTO POSITIVO",
    ru: "ПОЗИТИВНЫЙ ЖЕСТ",
    zh: "积极手势",
  },
  GENUINE: {
    id: "TULUS",
    de: "AUFRICHTIG",
    es: "GENUINO",
    fr: "AUTHENTIQUE",
    ja: "純粋",
    ko: "진정한",
    pt: "GENUÍNO",
    ru: "ПОДЛИННОСТЬ",
    zh: "真诚",
  },
  // afirmasi (affirmations)
  "I AM ENTHUSIASTIC": {
    id: "SAYA ANTUSIAS",
    de: "ICH BIN BEGEISTERT",
    es: "SOY ENTUSIASTA",
    fr: "JE SUIS ENTHOUSIASTE",
    ja: "私は情熱的",
    ko: "나는 열정적이다",
    pt: "EU SOU ENTUSIASMADO",
    ru: "Я ВДОХНОВЛЁН",
    zh: "我充满热情",
  },
  "I AM SPECIAL": {
    id: "SAYA ISTIMEWA",
    de: "ICH BIN BESONDERS",
    es: "SOY ESPECIAL",
    fr: "JE SUIS SPÉCIAL",
    ja: "私は特別",
    ko: "나는 특별하다",
    pt: "EU SOU ESPECIAL",
    ru: "Я ОСОБЕННЫЙ",
    zh: "我是独特的",
  },
  "I AM ABUNDANT": {
    id: "SAYA BERLIMPAH",
    de: "ICH BIN WOHLHABEND",
    es: "SOY ABUNDANTE",
    fr: "JE SUIS ABONDANT",
    ja: "私は豊か",
    ko: "나는 풍요롭다",
    pt: "EU SOU ABUNDANTE",
    ru: "Я ИЗОБИЛУЮ",
    zh: "我是丰盛的",
  },
  "I AM STRONG": {
    id: "SAYA KUAT",
    de: "ICH BIN STARK",
    es: "SOY FUERTE",
    fr: "JE SUIS FORT",
    ja: "私は強い",
    ko: "나는 강하다",
    pt: "EU SOU FORTE",
    ru: "Я СИЛЬНЫЙ",
    zh: "我是强大的",
  },
  "I AM UNIQUE": {
    id: "SAYA UNIK",
    de: "ICH BIN EINZIGARTIG",
    es: "SOY ÚNICO",
    fr: "JE SUIS UNIQUE",
    ja: "私は唯一",
    ko: "나는 독특하다",
    pt: "EU SOU ÚNICO",
    ru: "Я УНИКАЛЬНЫЙ",
    zh: "我是独一无二的",
  },
  "I AM COMPLETE": {
    id: "SAYA LENGKAP",
    de: "ICH BIN VOLLSTÄNDIG",
    es: "SOY COMPLETO",
    fr: "JE SUIS COMPLET",
    ja: "私は完全",
    ko: "나는 완전하다",
    pt: "EU SOU COMPLETO",
    ru: "Я ЦЕЛОСТНЫЙ",
    zh: "我是完整的",
  },
  "I AM FOCUSED": {
    id: "SAYA FOKUS",
    de: "ICH BIN FOKUSSIERT",
    es: "ESTOY ENFOCADO",
    fr: "JE SUIS CONCENTRÉ",
    ja: "私は集中している",
    ko: "나는 집중한다",
    pt: "EU SOU FOCADO",
    ru: "Я СОСРЕДОТОЧЕН",
    zh: "我是专注的",
  },
  "I AM OBEDIENT": {
    id: "SAYA PATUH",
    de: "ICH BIN FOLGSAM",
    es: "SOY OBEDIENTE",
    fr: "JE SUIS OBÉISSANT",
    ja: "私は従順",
    ko: "나는 순종적이다",
    pt: "EU SOU OBEDIENTE",
    ru: "Я ПОСЛУШНЫЙ",
    zh: "我是顺从的",
  },
  "I AM INSPIRED": {
    id: "SAYA TERINSPIRASI",
    de: "ICH BIN INSPIRIERT",
    es: "ESTOY INSPIRADO",
    fr: "JE SUIS INSPIRÉ",
    ja: "私はインスピレーションを受けている",
    ko: "나는 영감을 받았다",
    pt: "EU ESTOU INSPIRADO",
    ru: "Я ВДОХНОВЛЁН",
    zh: "我是受启发的",
  },
  "I AM VALUABLE": {
    id: "SAYA BERHARGA",
    de: "ICH BIN WERTVOLL",
    es: "SOY VALIOSO",
    fr: "JE SUIS PRÉCIEUX",
    ja: "私は価値がある",
    ko: "나는 소중하다",
    pt: "EU SOU VALIOSO",
    ru: "Я ЦЕННЫЙ",
    zh: "我是有价值的",
  },
  "I AM BALANCED": {
    id: "SAYA SEIMBANG",
    de: "ICH BIN AUSGEGLICHEN",
    es: "ESTOY EQUILIBRADO",
    fr: "JE SUIS ÉQUILIBRÉ",
    ja: "私はバランスが取れている",
    ko: "나는 균형 잡혔다",
    pt: "EU SOU EQUILIBRADO",
    ru: "Я УРАВНОВЕШЕН",
    zh: "我是平衡的",
  },
  // tri_wara / siklus (cycle steps)
  INPUT: {
    id: "MASUKAN",
    de: "EINGABE",
    es: "ENTRADA",
    fr: "ENTRÉE",
    ja: "インプット",
    ko: "입력",
    pt: "ENTRADA",
    ru: "ВВОД",
    zh: "输入",
  },
  PROCESS: {
    id: "PROSES",
    de: "PROZESS",
    es: "PROCESO",
    fr: "PROCESSUS",
    ja: "プロセス",
    ko: "처리",
    pt: "PROCESSO",
    ru: "ПРОЦЕСС",
    zh: "处理",
  },
  OUTPUT: {
    id: "KELUARAN",
    de: "AUSGABE",
    es: "SALIDA",
    fr: "SORTIE",
    ja: "アウトプット",
    ko: "출력",
    pt: "SAÍDA",
    ru: "ВЫХОД",
    zh: "输出",
  },
  // catur_wara / kanda_pat (four inner voices)
  EMOTION: {
    id: "EMOSI",
    de: "EMOTION",
    es: "EMOCIÓN",
    fr: "ÉMOTION",
    ja: "感情",
    ko: "감정",
    pt: "EMOÇÃO",
    ru: "ЭМОЦИЯ",
    zh: "情感",
  },
  INTELLIGENCE: {
    id: "KECERDASAN",
    de: "INTELLIGENZ",
    es: "INTELIGENCIA",
    fr: "INTELLIGENCE",
    ja: "知性",
    ko: "지성",
    pt: "INTELIGÊNCIA",
    ru: "ИНТЕЛЛЕКТ",
    zh: "智慧",
  },
  CONSCIENCE: {
    id: "HATI NURANI",
    de: "GEWISSEN",
    es: "CONCIENCIA",
    fr: "CONSCIENCE",
    ja: "良心",
    ko: "양심",
    pt: "CONSCIÊNCIA",
    ru: "СОВЕСТЬ",
    zh: "良知",
  },
  INSTINCT: {
    id: "INSTING",
    de: "INSTINKT",
    es: "INSTINTO",
    fr: "INSTINCT",
    ja: "本能",
    ko: "본능",
    pt: "INSTINTO",
    ru: "ИНСТИНКТ",
    zh: "本能",
  },
  // panca_tirta (five vital organs)
  LIVER: {
    id: "HATI",
    de: "LEBER",
    es: "HÍGADO",
    fr: "FOIE",
    ja: "肝臓",
    ko: "간",
    pt: "FÍGADO",
    ru: "ПЕЧЕНЬ",
    zh: "肝",
  },
  HEART: {
    id: "JANTUNG",
    de: "HERZ",
    es: "CORAZÓN",
    fr: "CŒUR",
    ja: "心臓",
    ko: "심장",
    pt: "CORAÇÃO",
    ru: "СЕРДЦЕ",
    zh: "心",
  },
  SPLEEN: {
    id: "LIMPA",
    de: "MILZ",
    es: "BAZO",
    fr: "RATE",
    ja: "脾臓",
    ko: "비장",
    pt: "BAÇO",
    ru: "СЕЛЕЗЁНКА",
    zh: "脾",
  },
  LUNG: {
    id: "PARU-PARU",
    de: "LUNGE",
    es: "PULMÓN",
    fr: "POUMON",
    ja: "肺",
    ko: "폐",
    pt: "PULMÃO",
    ru: "ЛЁГКИЕ",
    zh: "肺",
  },
  KIDNEY: {
    id: "GINJAL",
    de: "NIERE",
    es: "RIÑÓN",
    fr: "REIN",
    ja: "腎臓",
    ko: "신장",
    pt: "RIM",
    ru: "ПОЧКА",
    zh: "肾",
  },
  // panca_brahma (five digestive organs)
  "LARGE INTESTINE": {
    id: "USUS BESAR",
    de: "DICKDARM",
    es: "INTESTINO GRUESO",
    fr: "GROS INTESTIN",
    ja: "大腸",
    ko: "대장",
    pt: "INTESTINO GROSSO",
    ru: "ТОЛСТАЯ КИШКА",
    zh: "大肠",
  },
  BLADDER: {
    id: "KANDUNG KEMIH",
    de: "BLASE",
    es: "VEJIGA",
    fr: "VESSIE",
    ja: "膀胱",
    ko: "방광",
    pt: "BEXIGA",
    ru: "МОЧЕВОЙ ПУЗЫРЬ",
    zh: "膀胱",
  },
  GALLBLADDER: {
    id: "KANDUNG EMPEDU",
    de: "GALLENBLASE",
    es: "VESÍCULA BILIAR",
    fr: "VÉSICULE BILIAIRE",
    ja: "胆嚢",
    ko: "담낭",
    pt: "VESÍCULA BILIAR",
    ru: "ЖЕЛЧНЫЙ ПУЗЫРЬ",
    zh: "胆囊",
  },
  "SMALL INTESTINE": {
    id: "USUS HALUS",
    de: "DÜNNDARM",
    es: "INTESTINO DELGADO",
    fr: "INTESTIN GRÊLE",
    ja: "小腸",
    ko: "소장",
    pt: "INTESTINO DELGADO",
    ru: "ТОНКАЯ КИШКА",
    zh: "小肠",
  },
  STOMACH: {
    id: "LAMBUNG",
    de: "MAGEN",
    es: "ESTÓMAGO",
    fr: "ESTOMAC",
    ja: "胃",
    ko: "위",
    pt: "ESTÔMAGO",
    ru: "ЖЕЛУДОК",
    zh: "胃",
  },
  // dasa_aksara (ten cosmic forces)
  "DEITY/YANG": {
    id: "DEWA/YANG",
    de: "GOTTHEIT/YANG",
    es: "DEIDAD/YANG",
    fr: "DIVINITÉ/YANG",
    ja: "神/陽",
    ko: "신/양",
    pt: "DIVINDADE/YANG",
    ru: "БОЖЕСТВО/ЯН",
    zh: "神/阳",
  },
  HUMAN: {
    id: "MANUSIA",
    de: "MENSCH",
    es: "HUMANO",
    fr: "HUMAIN",
    ja: "人間",
    ko: "인간",
    pt: "HUMANO",
    ru: "ЧЕЛОВЕК",
    zh: "人",
  },
  GIANT: {
    id: "RAKSASA",
    de: "RIESE",
    es: "GIGANTE",
    fr: "GÉANT",
    ja: "巨人",
    ko: "거인",
    pt: "GIGANTE",
    ru: "ВЕЛИКАН",
    zh: "巨人",
  },
  DEITY: {
    id: "DEWA",
    de: "GOTTHEIT",
    es: "DEIDAD",
    fr: "DIVINITÉ",
    ja: "神",
    ko: "신",
    pt: "DIVINDADE",
    ru: "БОЖЕСТВО",
    zh: "神",
  },
  "BRAHMA/YANG": {
    id: "BRAHMA/YANG",
    de: "BRAHMA/YANG",
    es: "BRAHMA/YANG",
    fr: "BRAHMA/YANG",
    ja: "ブラフマー/陽",
    ko: "브라흐마/양",
    pt: "BRAHMA/YANG",
    ru: "БРАХМА/ЯН",
    zh: "梵天/阳",
  },
  KALA: {
    id: "KALA",
    de: "KALA",
    es: "KALA",
    fr: "KALA",
    ja: "カラ",
    ko: "칼라",
    pt: "KALA",
    ru: "КАЛА",
    zh: "时间神",
  },
  UMA: {
    id: "UMA",
    de: "UMA",
    es: "UMA",
    fr: "UMA",
    ja: "ウマ",
    ko: "우마",
    pt: "UMA",
    ru: "УМА",
    zh: "乌玛",
  },
  SRI: {
    id: "SRI",
    de: "SRI",
    es: "SRI",
    fr: "SRI",
    ja: "スリ",
    ko: "스리",
    pt: "SRI",
    ru: "ШРИ",
    zh: "吉祥天",
  },
  "WATER/YIN": {
    id: "AIR/YIN",
    de: "WASSER/YIN",
    es: "AGUA/YIN",
    fr: "EAU/YIN",
    ja: "水/陰",
    ko: "물/음",
    pt: "ÁGUA/YIN",
    ru: "ВОДА/ИНЬ",
    zh: "水/阴",
  },
  // urip (energy value label)
  urip: {
    id: "URIP",
    de: "URIP",
    es: "URIP",
    fr: "URIP",
    ja: "エネルギー値",
    ko: "에너지값",
    pt: "URIP",
    ru: "УРИП",
    zh: "能量值",
  },
  // sapta_wara (day names)
  SATURDAY: {
    id: "SABTU",
    de: "SAMSTAG",
    es: "SÁBADO",
    fr: "SAMEDI",
    ja: "土曜日",
    ko: "토요일",
    pt: "SÁBADO",
    ru: "СУББОТА",
    zh: "星期六",
  },
  FRIDAY: {
    id: "JUMAT",
    de: "FREITAG",
    es: "VIERNES",
    fr: "VENDREDI",
    ja: "金曜日",
    ko: "금요일",
    pt: "SEXTA-FEIRA",
    ru: "ПЯТНИЦА",
    zh: "星期五",
  },
  THURSDAY: {
    id: "KAMIS",
    de: "DONNERSTAG",
    es: "JUEVES",
    fr: "JEUDI",
    ja: "木曜日",
    ko: "목요일",
    pt: "QUINTA-FEIRA",
    ru: "ЧЕТВЕРГ",
    zh: "星期四",
  },
  WEDNESDAY: {
    id: "RABU",
    de: "MITTWOCH",
    es: "MIÉRCOLES",
    fr: "MERCREDI",
    ja: "水曜日",
    ko: "수요일",
    pt: "QUARTA-FEIRA",
    ru: "СРЕДА",
    zh: "星期三",
  },
  TUESDAY: {
    id: "SELASA",
    de: "DIENSTAG",
    es: "MARTES",
    fr: "MARDI",
    ja: "火曜日",
    ko: "화요일",
    pt: "TERÇA-FEIRA",
    ru: "ВТОРНИК",
    zh: "星期二",
  },
  MONDAY: {
    id: "SENIN",
    de: "MONTAG",
    es: "LUNES",
    fr: "LUNDI",
    ja: "月曜日",
    ko: "월요일",
    pt: "SEGUNDA-FEIRA",
    ru: "ПОНЕДЕЛЬНИК",
    zh: "星期一",
  },
  SUNDAY: {
    id: "MINGGU",
    de: "SONNTAG",
    es: "DOMINGO",
    fr: "DIMANCHE",
    ja: "日曜日",
    ko: "일요일",
    pt: "DOMINGO",
    ru: "ВОСКРЕСЕНЬЕ",
    zh: "星期日",
  },
  // panca_wara (5-day market cycle - Balinese names, transliterated for CJK)
  PAHING: {
    id: "PAHING",
    de: "PAHING",
    es: "PAHING",
    fr: "PAHING",
    ja: "パヒン",
    ko: "파힝",
    pt: "PAHING",
    ru: "ПАХИНГ",
    zh: "帕欣",
  },
  UMANIS: {
    id: "UMANIS",
    de: "UMANIS",
    es: "UMANIS",
    fr: "UMANIS",
    ja: "ウマニス",
    ko: "우마니스",
    pt: "UMANIS",
    ru: "УМАНИС",
    zh: "乌曼尼斯",
  },
  KLIWON: {
    id: "KLIWON",
    de: "KLIWON",
    es: "KLIWON",
    fr: "KLIWON",
    ja: "クリウォン",
    ko: "클리원",
    pt: "KLIWON",
    ru: "КЛИВОН",
    zh: "克利翁",
  },
  WAGE: {
    id: "WAGE",
    de: "WAGE",
    es: "WAGE",
    fr: "WAGE",
    ja: "ワゲ",
    ko: "와게",
    pt: "WAGE",
    ru: "ВАГЕ",
    zh: "瓦格",
  },
  PON: {
    id: "PON",
    de: "PON",
    es: "PON",
    fr: "PON",
    ja: "ポン",
    ko: "폰",
    pt: "PON",
    ru: "ПОН",
    zh: "蓬",
  },
  // sad_wara (6-day cycle - Balinese names, transliterated for CJK)
  ARIYANG: {
    id: "ARIYANG",
    de: "ARIYANG",
    es: "ARIYANG",
    fr: "ARIYANG",
    ja: "アリヤン",
    ko: "아리양",
    pt: "ARIYANG",
    ru: "АРИЯНГ",
    zh: "阿里扬",
  },
  TUNGLEH: {
    id: "TUNGLEH",
    de: "TUNGLEH",
    es: "TUNGLEH",
    fr: "TUNGLEH",
    ja: "トゥンレ",
    ko: "퉁레",
    pt: "TUNGLEH",
    ru: "ТУНГЛЕ",
    zh: "通勒",
  },
  MAULU: {
    id: "MAULU",
    de: "MAULU",
    es: "MAULU",
    fr: "MAULU",
    ja: "マウル",
    ko: "마울루",
    pt: "MAULU",
    ru: "МАУЛУ",
    zh: "马乌卢",
  },
  WAS: {
    id: "WAS",
    de: "WAS",
    es: "WAS",
    fr: "WAS",
    ja: "ワス",
    ko: "와스",
    pt: "WAS",
    ru: "ВАС",
    zh: "瓦斯",
  },
  PANIRON: {
    id: "PANIRON",
    de: "PANIRON",
    es: "PANIRON",
    fr: "PANIRON",
    ja: "パニロン",
    ko: "파니론",
    pt: "PANIRON",
    ru: "ПАНИРОН",
    zh: "帕尼龙",
  },
  URUKUNG: {
    id: "URUKUNG",
    de: "URUKUNG",
    es: "URUKUNG",
    fr: "URUKUNG",
    ja: "ウルクン",
    ko: "우루쿵",
    pt: "URUKUNG",
    ru: "УРУКУНГ",
    zh: "乌鲁恭",
  },
  // wuku (30 Balinese calendar weeks - transliterated for CJK)
  WARIGADEAN: {
    id: "WARIGADEAN",
    de: "WARIGADEAN",
    es: "WARIGADEAN",
    fr: "WARIGADEAN",
    ja: "ワリガデアン",
    ko: "와리가데안",
    pt: "WARIGADEAN",
    ru: "ВАРИГАДЕАН",
    zh: "瓦里加迪安",
  },
  WARIGA: {
    id: "WARIGA",
    de: "WARIGA",
    es: "WARIGA",
    fr: "WARIGA",
    ja: "ワリガ",
    ko: "와리가",
    pt: "WARIGA",
    ru: "ВАРИГА",
    zh: "瓦里加",
  },
  GUMBREG: {
    id: "GUMBREG",
    de: "GUMBREG",
    es: "GUMBREG",
    fr: "GUMBREG",
    ja: "グンブレグ",
    ko: "굼브렉",
    pt: "GUMBREG",
    ru: "ГУМБРЕГ",
    zh: "贡布雷格",
  },
  TOLU: {
    id: "TOLU",
    de: "TOLU",
    es: "TOLU",
    fr: "TOLU",
    ja: "トル",
    ko: "톨루",
    pt: "TOLU",
    ru: "ТОЛУ",
    zh: "托卢",
  },
  KULANTIR: {
    id: "KULANTIR",
    de: "KULANTIR",
    es: "KULANTIR",
    fr: "KULANTIR",
    ja: "クランティル",
    ko: "쿨란티르",
    pt: "KULANTIR",
    ru: "КУЛАНТИР",
    zh: "库兰提尔",
  },
  UKIR: {
    id: "UKIR",
    de: "UKIR",
    es: "UKIR",
    fr: "UKIR",
    ja: "ウキル",
    ko: "우키르",
    pt: "UKIR",
    ru: "УКИР",
    zh: "乌基尔",
  },
  LANDEP: {
    id: "LANDEP",
    de: "LANDEP",
    es: "LANDEP",
    fr: "LANDEP",
    ja: "ランデプ",
    ko: "란덥",
    pt: "LANDEP",
    ru: "ЛАНДЕП",
    zh: "兰德普",
  },
  SINTA: {
    id: "SINTA",
    de: "SINTA",
    es: "SINTA",
    fr: "SINTA",
    ja: "シンタ",
    ko: "신타",
    pt: "SINTA",
    ru: "СИНТА",
    zh: "辛塔",
  },
  WATUGUNUNG: {
    id: "WATUGUNUNG",
    de: "WATUGUNUNG",
    es: "WATUGUNUNG",
    fr: "WATUGUNUNG",
    ja: "ワトゥグヌン",
    ko: "와투구눙",
    pt: "WATUGUNUNG",
    ru: "ВАТУГУНУНГ",
    zh: "瓦图古农",
  },
  DUKUT: {
    id: "DUKUT",
    de: "DUKUT",
    es: "DUKUT",
    fr: "DUKUT",
    ja: "ドゥクット",
    ko: "두쿳",
    pt: "DUKUT",
    ru: "ДУКУТ",
    zh: "杜库特",
  },
  KELAWU: {
    id: "KELAWU",
    de: "KELAWU",
    es: "KELAWU",
    fr: "KELAWU",
    ja: "クラウ",
    ko: "클라우",
    pt: "KELAWU",
    ru: "КЕЛАВУ",
    zh: "克拉乌",
  },
  WAYANG: {
    id: "WAYANG",
    de: "WAYANG",
    es: "WAYANG",
    fr: "WAYANG",
    ja: "ワヤン",
    ko: "와양",
    pt: "WAYANG",
    ru: "ВАЯНГ",
    zh: "哇扬",
  },
  UGU: {
    id: "UGU",
    de: "UGU",
    es: "UGU",
    fr: "UGU",
    ja: "ウグ",
    ko: "우구",
    pt: "UGU",
    ru: "УГУ",
    zh: "乌古",
  },
  BALA: {
    id: "BALA",
    de: "BALA",
    es: "BALA",
    fr: "BALA",
    ja: "バラ",
    ko: "발라",
    pt: "BALA",
    ru: "БАЛА",
    zh: "巴拉",
  },
  PERANGBAKAT: {
    id: "PERANGBAKAT",
    de: "PERANGBAKAT",
    es: "PERANGBAKAT",
    fr: "PERANGBAKAT",
    ja: "ペランバカット",
    ko: "페랑바캇",
    pt: "PERANGBAKAT",
    ru: "ПЕРАНГБАКАТ",
    zh: "佩朗巴卡特",
  },
  MENAIL: {
    id: "MENAIL",
    de: "MENAIL",
    es: "MENAIL",
    fr: "MENAIL",
    ja: "ムナイル",
    ko: "므나일",
    pt: "MENAIL",
    ru: "МЕНАИЛ",
    zh: "梅奈尔",
  },
  UYE: {
    id: "UYE",
    de: "UYE",
    es: "UYE",
    fr: "UYE",
    ja: "ウイェ",
    ko: "우예",
    pt: "UYE",
    ru: "УЙЕ",
    zh: "乌耶",
  },
  MATAL: {
    id: "MATAL",
    de: "MATAL",
    es: "MATAL",
    fr: "MATAL",
    ja: "マタル",
    ko: "마탈",
    pt: "MATAL",
    ru: "МАТАЛ",
    zh: "马塔尔",
  },
  MEDANGKUNGAN: {
    id: "MEDANGKUNGAN",
    de: "MEDANGKUNGAN",
    es: "MEDANGKUNGAN",
    fr: "MEDANGKUNGAN",
    ja: "ムダンクンガン",
    ko: "므당꿍안",
    pt: "MEDANGKUNGAN",
    ru: "МЕДАНГКУНГАН",
    zh: "梅当昆安",
  },
  TAMBIR: {
    id: "TAMBIR",
    de: "TAMBIR",
    es: "TAMBIR",
    fr: "TAMBIR",
    ja: "タンビル",
    ko: "탐비르",
    pt: "TAMBIR",
    ru: "ТАМБИР",
    zh: "坦比尔",
  },
  MERAKIH: {
    id: "MERAKIH",
    de: "MERAKIH",
    es: "MERAKIH",
    fr: "MERAKIH",
    ja: "ムラキ",
    ko: "므라키",
    pt: "MERAKIH",
    ru: "МЕРАКИХ",
    zh: "梅拉基",
  },
  KRULUT: {
    id: "KRULUT",
    de: "KRULUT",
    es: "KRULUT",
    fr: "KRULUT",
    ja: "クルルット",
    ko: "크룰룻",
    pt: "KRULUT",
    ru: "КРУЛУТ",
    zh: "克鲁卢特",
  },
  PAHANG: {
    id: "PAHANG",
    de: "PAHANG",
    es: "PAHANG",
    fr: "PAHANG",
    ja: "パハン",
    ko: "파항",
    pt: "PAHANG",
    ru: "ПАХАНГ",
    zh: "巴杭",
  },
  PUJUT: {
    id: "PUJUT",
    de: "PUJUT",
    es: "PUJUT",
    fr: "PUJUT",
    ja: "プジュット",
    ko: "푸줏",
    pt: "PUJUT",
    ru: "ПУДЖУТ",
    zh: "普朱特",
  },
  MEDANGSIA: {
    id: "MEDANGSIA",
    de: "MEDANGSIA",
    es: "MEDANGSIA",
    fr: "MEDANGSIA",
    ja: "ムダンシア",
    ko: "므당시아",
    pt: "MEDANGSIA",
    ru: "МЕДАНГСИА",
    zh: "梅当西亚",
  },
  LANGKIR: {
    id: "LANGKIR",
    de: "LANGKIR",
    es: "LANGKIR",
    fr: "LANGKIR",
    ja: "ランキル",
    ko: "랑키르",
    pt: "LANGKIR",
    ru: "ЛАНГКИР",
    zh: "兰基尔",
  },
  KUNINGAN: {
    id: "KUNINGAN",
    de: "KUNINGAN",
    es: "KUNINGAN",
    fr: "KUNINGAN",
    ja: "クニンガン",
    ko: "쿠닝안",
    pt: "KUNINGAN",
    ru: "КУНИНГАН",
    zh: "库宁安",
  },
  DUNGULAN: {
    id: "DUNGULAN",
    de: "DUNGULAN",
    es: "DUNGULAN",
    fr: "DUNGULAN",
    ja: "ドゥングラン",
    ko: "둥울란",
    pt: "DUNGULAN",
    ru: "ДУНГУЛАН",
    zh: "敦古兰",
  },
  SUNGSANG: {
    id: "SUNGSANG",
    de: "SUNGSANG",
    es: "SUNGSANG",
    fr: "SUNGSANG",
    ja: "スンサン",
    ko: "숭상",
    pt: "SUNGSANG",
    ru: "СУНГСАНГ",
    zh: "松桑",
  },
  JULUNGWANGI: {
    id: "JULUNGWANGI",
    de: "JULUNGWANGI",
    es: "JULUNGWANGI",
    fr: "JULUNGWANGI",
    ja: "ジュルンワンギ",
    ko: "줄룽왕이",
    pt: "JULUNGWANGI",
    ru: "ДЖУЛУНГВАНГИ",
    zh: "朱隆旺吉",
  },
};
