/* eslint-disable max-lines */
/**
 * Translations for database terms that appear in AI responses.
 * These Balinese/English terms from database.ts need to be rendered
 * in the user's language when the AI mentions them.
 */
export const TERM_TRANSLATIONS: Record<string, Record<string, string>> = {
  // lahir_untuk / diberi_hak_untuk names
  GURU: {
    id: "Guru",
    de: "Guru",
    es: "Guru",
    fr: "Guru",
    ja: "グル",
    ko: "구루",
    pt: "Guru",
    ru: "Гуру",
    zh: "导师",
  },
  RATU: {
    id: "Ratu",
    de: "Ratu",
    es: "Ratu",
    fr: "Ratu",
    ja: "ラトゥ",
    ko: "라투",
    pt: "Ratu",
    ru: "Рату",
    zh: "守护者",
  },
  LARA: {
    id: "Lara",
    de: "Lara",
    es: "Lara",
    fr: "Lara",
    ja: "ララ",
    ko: "라라",
    pt: "Lara",
    ru: "Лара",
    zh: "成长",
  },
  PATI: {
    id: "Pati",
    de: "Pati",
    es: "Pati",
    fr: "Pati",
    ja: "パティ",
    ko: "파티",
    pt: "Pati",
    ru: "Пати",
    zh: "解脱",
  },
  // lahir_untuk descriptions
  GUIDING: {
    id: "Membimbing",
    de: "Führend",
    es: "Guiando",
    fr: "Guidant",
    ja: "導く",
    ko: "안내",
    pt: "Guiando",
    ru: "Направляющий",
    zh: "引导",
  },
  PROTECTING: {
    id: "Melindungi",
    de: "Schützend",
    es: "Protegiendo",
    fr: "Protégeant",
    ja: "守る",
    ko: "보호",
    pt: "Protegendo",
    ru: "Защищающий",
    zh: "保护",
  },
  GROWING: {
    id: "Bertumbuh",
    de: "Wachsend",
    es: "Creciendo",
    fr: "Grandissant",
    ja: "成長する",
    ko: "성장",
    pt: "Crescendo",
    ru: "Растущий",
    zh: "成长",
  },
  RELEASING: {
    id: "Melepaskan",
    de: "Loslassend",
    es: "Liberando",
    fr: "Libérant",
    ja: "解放する",
    ko: "해방",
    pt: "Liberando",
    ru: "Освобождающий",
    zh: "释放",
  },
  // tindakan (actions)
  MINDFULNESS: {
    id: "Kesadaran",
    de: "Achtsamkeit",
    es: "Atención plena",
    fr: "Pleine conscience",
    ja: "マインドフルネス",
    ko: "마음챙김",
    pt: "Atenção plena",
    ru: "Осознанность",
    zh: "正念",
  },
  WORSHIP: {
    id: "Ibadah",
    de: "Andacht",
    es: "Devoción",
    fr: "Dévotion",
    ja: "礼拝",
    ko: "예배",
    pt: "Devoção",
    ru: "Поклонение",
    zh: "祈祷",
  },
  PROBIOTIC: {
    id: "Probiotik",
    de: "Probiotisch",
    es: "Probiótico",
    fr: "Probiotique",
    ja: "プロバイオティクス",
    ko: "프로바이오틱",
    pt: "Probiótico",
    ru: "Пробиотик",
    zh: "益生菌",
  },
  SERVICE: {
    id: "Pelayanan",
    de: "Dienst",
    es: "Servicio",
    fr: "Service",
    ja: "奉仕",
    ko: "봉사",
    pt: "Serviço",
    ru: "Служение",
    zh: "服务",
  },
  "CLEAN UP": {
    id: "Bersih-bersih",
    de: "Aufräumen",
    es: "Limpiar",
    fr: "Nettoyage",
    ja: "浄化",
    ko: "정화",
    pt: "Limpeza",
    ru: "Очищение",
    zh: "清理",
  },
  "DEEP SLEEP": {
    id: "Tidur Nyenyak",
    de: "Tiefschlaf",
    es: "Sueño profundo",
    fr: "Sommeil profond",
    ja: "深い眠り",
    ko: "깊은 수면",
    pt: "Sono profundo",
    ru: "Глубокий сон",
    zh: "深度睡眠",
  },
  // cipta (psychosocial)
  TRUST: {
    id: "Kepercayaan",
    de: "Vertrauen",
    es: "Confianza",
    fr: "Confiance",
    ja: "信頼",
    ko: "신뢰",
    pt: "Confiança",
    ru: "Доверие",
    zh: "信任",
  },
  AUTONOMY: {
    id: "Otonomi",
    de: "Autonomie",
    es: "Autonomía",
    fr: "Autonomie",
    ja: "自律",
    ko: "자율성",
    pt: "Autonomia",
    ru: "Автономия",
    zh: "自主",
  },
  INITIATIVE: {
    id: "Inisiatif",
    de: "Initiative",
    es: "Iniciativa",
    fr: "Initiative",
    ja: "主導権",
    ko: "주도성",
    pt: "Iniciativa",
    ru: "Инициатива",
    zh: "主动",
  },
  DILIGENT: {
    id: "Rajin",
    de: "Fleißig",
    es: "Diligente",
    fr: "Diligent",
    ja: "勤勉",
    ko: "근면",
    pt: "Diligente",
    ru: "Усердие",
    zh: "勤奋",
  },
  IDENTITY: {
    id: "Identitas",
    de: "Identität",
    es: "Identidad",
    fr: "Identité",
    ja: "アイデンティティ",
    ko: "정체성",
    pt: "Identidade",
    ru: "Идентичность",
    zh: "认同",
  },
  INTIMATE: {
    id: "Keintiman",
    de: "Intimität",
    es: "Intimidad",
    fr: "Intimité",
    ja: "親密",
    ko: "친밀",
    pt: "Intimidade",
    ru: "Близость",
    zh: "亲密",
  },
  DYNAMIC: {
    id: "Dinamis",
    de: "Dynamisch",
    es: "Dinámico",
    fr: "Dynamique",
    ja: "ダイナミック",
    ko: "역동적",
    pt: "Dinâmico",
    ru: "Динамика",
    zh: "活力",
  },
  INTEGRITY: {
    id: "Integritas",
    de: "Integrität",
    es: "Integridad",
    fr: "Intégrité",
    ja: "誠実",
    ko: "성실",
    pt: "Integridade",
    ru: "Честность",
    zh: "正直",
  },
  // rasa (emotional)
  PEACE: {
    id: "Damai",
    de: "Frieden",
    es: "Paz",
    fr: "Paix",
    ja: "平和",
    ko: "평화",
    pt: "Paz",
    ru: "Покой",
    zh: "平和",
  },
  APATHY: {
    id: "Apatis",
    de: "Apathie",
    es: "Apatía",
    fr: "Apathie",
    ja: "無感動",
    ko: "무관심",
    pt: "Apatia",
    ru: "Апатия",
    zh: "冷漠",
  },
  ANGER: {
    id: "Marah",
    de: "Wut",
    es: "Ira",
    fr: "Colère",
    ja: "怒り",
    ko: "분노",
    pt: "Raiva",
    ru: "Гнев",
    zh: "愤怒",
  },
  GRIEF: {
    id: "Duka",
    de: "Trauer",
    es: "Dolor",
    fr: "Chagrin",
    ja: "悲嘆",
    ko: "슬픔",
    pt: "Luto",
    ru: "Горе",
    zh: "悲伤",
  },
  PRIDE: {
    id: "Bangga",
    de: "Stolz",
    es: "Orgullo",
    fr: "Fierté",
    ja: "誇り",
    ko: "자부심",
    pt: "Orgulho",
    ru: "Гордость",
    zh: "自豪",
  },
  PASSION: {
    id: "Gairah",
    de: "Leidenschaft",
    es: "Pasión",
    fr: "Passion",
    ja: "情熱",
    ko: "열정",
    pt: "Paixão",
    ru: "Страсть",
    zh: "热情",
  },
  FEAR: {
    id: "Takut",
    de: "Angst",
    es: "Miedo",
    fr: "Peur",
    ja: "恐れ",
    ko: "두려움",
    pt: "Medo",
    ru: "Страх",
    zh: "恐惧",
  },
  FIRM: {
    id: "Teguh",
    de: "Fest",
    es: "Firme",
    fr: "Ferme",
    ja: "堅固",
    ko: "확고",
    pt: "Firme",
    ru: "Стойкость",
    zh: "坚定",
  },
  SINCERE: {
    id: "Tulus",
    de: "Aufrichtig",
    es: "Sincero",
    fr: "Sincère",
    ja: "誠実",
    ko: "진심",
    pt: "Sincero",
    ru: "Искренность",
    zh: "真诚",
  },
  // karsa (behavioral)
  LISTENING: {
    id: "Mendengarkan",
    de: "Zuhören",
    es: "Escuchar",
    fr: "Écouter",
    ja: "傾聴",
    ko: "경청",
    pt: "Ouvir",
    ru: "Слушание",
    zh: "倾听",
  },
  SHARING: {
    id: "Berbagi",
    de: "Teilen",
    es: "Compartir",
    fr: "Partager",
    ja: "共有",
    ko: "나눔",
    pt: "Compartilhar",
    ru: "Делиться",
    zh: "分享",
  },
  EMPATHY: {
    id: "Empati",
    de: "Empathie",
    es: "Empatía",
    fr: "Empathie",
    ja: "共感",
    ko: "공감",
    pt: "Empatia",
    ru: "Эмпатия",
    zh: "共情",
  },
  "GESTURE(+)": {
    id: "Gestur Positif",
    de: "Positive Geste",
    es: "Gesto positivo",
    fr: "Geste positif",
    ja: "ポジティブジェスチャー",
    ko: "긍정적 제스처",
    pt: "Gesto positivo",
    ru: "Позитивный жест",
    zh: "积极手势",
  },
  GENUINE: {
    id: "Tulus",
    de: "Aufrichtig",
    es: "Genuino",
    fr: "Authentique",
    ja: "純粋",
    ko: "진정한",
    pt: "Genuíno",
    ru: "Подлинность",
    zh: "真诚",
  },
  // afirmasi (affirmations)
  "I AM ENTHUSIASTIC": {
    id: "SAYA ANTUSIAS",
    de: "ICH BIN BEGEISTERT",
    es: "SOY ENTUSIASTA",
    fr: "JE SUIS ENTHOUSIASTE",
    ja: "私は情熱的",
    ko: "나는 열정적이다",
    pt: "EU SOU ENTUSIASMADO",
    ru: "Я ВДОХНОВЛЁН",
    zh: "我充满热情",
  },
  "I AM SPECIAL": {
    id: "SAYA ISTIMEWA",
    de: "ICH BIN BESONDERS",
    es: "SOY ESPECIAL",
    fr: "JE SUIS SPÉCIAL",
    ja: "私は特別",
    ko: "나는 특별하다",
    pt: "EU SOU ESPECIAL",
    ru: "Я ОСОБЕННЫЙ",
    zh: "我是独特的",
  },
  "I AM ABUNDANT": {
    id: "SAYA BERLIMPAH",
    de: "ICH BIN WOHLHABEND",
    es: "SOY ABUNDANTE",
    fr: "JE SUIS ABONDANT",
    ja: "私は豊か",
    ko: "나는 풍요롭다",
    pt: "EU SOU ABUNDANTE",
    ru: "Я ИЗОБИЛУЮ",
    zh: "我是丰盛的",
  },
  "I AM STRONG": {
    id: "SAYA KUAT",
    de: "ICH BIN STARK",
    es: "SOY FUERTE",
    fr: "JE SUIS FORT",
    ja: "私は強い",
    ko: "나는 강하다",
    pt: "EU SOU FORTE",
    ru: "Я СИЛЬНЫЙ",
    zh: "我是强大的",
  },
  "I AM UNIQUE": {
    id: "SAYA UNIK",
    de: "ICH BIN EINZIGARTIG",
    es: "SOY ÚNICO",
    fr: "JE SUIS UNIQUE",
    ja: "私は唯一",
    ko: "나는 독특하다",
    pt: "EU SOU ÚNICO",
    ru: "Я УНИКАЛЬНЫЙ",
    zh: "我是独一无二的",
  },
  "I AM COMPLETE": {
    id: "SAYA LENGKAP",
    de: "ICH BIN VOLLSTÄNDIG",
    es: "SOY COMPLETO",
    fr: "JE SUIS COMPLET",
    ja: "私は完全",
    ko: "나는 완전하다",
    pt: "EU SOU COMPLETO",
    ru: "Я ЦЕЛОСТНЫЙ",
    zh: "我是完整的",
  },
  "I AM FOCUSED": {
    id: "SAYA FOKUS",
    de: "ICH BIN FOKUSSIERT",
    es: "ESTOY ENFOCADO",
    fr: "JE SUIS CONCENTRÉ",
    ja: "私は集中している",
    ko: "나는 집중한다",
    pt: "EU SOU FOCADO",
    ru: "Я СОСРЕДОТОЧЕН",
    zh: "我是专注的",
  },
  "I AM OBEDIENT": {
    id: "SAYA PATUH",
    de: "ICH BIN FOLGSAM",
    es: "SOY OBEDIENTE",
    fr: "JE SUIS OBÉISSANT",
    ja: "私は従順",
    ko: "나는 순종적이다",
    pt: "EU SOU OBEDIENTE",
    ru: "Я ПОСЛУШНЫЙ",
    zh: "我是顺从的",
  },
  "I AM INSPIRED": {
    id: "SAYA TERINSPIRASI",
    de: "ICH BIN INSPIRIERT",
    es: "ESTOY INSPIRADO",
    fr: "JE SUIS INSPIRÉ",
    ja: "私はインスピレーションを受けている",
    ko: "나는 영감을 받았다",
    pt: "EU ESTOU INSPIRADO",
    ru: "Я ВДОХНОВЛЁН",
    zh: "我是受启发的",
  },
  "I AM VALUABLE": {
    id: "SAYA BERHARGA",
    de: "ICH BIN WERTVOLL",
    es: "SOY VALIOSO",
    fr: "JE SUIS PRÉCIEUX",
    ja: "私は価値がある",
    ko: "나는 소중하다",
    pt: "EU SOU VALIOSO",
    ru: "Я ЦЕННЫЙ",
    zh: "我是有价值的",
  },
  "I AM BALANCED": {
    id: "SAYA SEIMBANG",
    de: "ICH BIN AUSGEGLICHEN",
    es: "ESTOY EQUILIBRADO",
    fr: "JE SUIS ÉQUILIBRÉ",
    ja: "私はバランスが取れている",
    ko: "나는 균형 잡혔다",
    pt: "EU SOU EQUILIBRADO",
    ru: "Я УРАВНОВЕШЕН",
    zh: "我是平衡的",
  },
  // tri_wara / siklus (cycle steps)
  INPUT: {
    id: "Masukan",
    de: "Eingabe",
    es: "Entrada",
    fr: "Entrée",
    ja: "インプット",
    ko: "입력",
    pt: "Entrada",
    ru: "Ввод",
    zh: "输入",
  },
  PROCESS: {
    id: "Proses",
    de: "Prozess",
    es: "Proceso",
    fr: "Processus",
    ja: "プロセス",
    ko: "처리",
    pt: "Processo",
    ru: "Процесс",
    zh: "处理",
  },
  OUTPUT: {
    id: "Keluaran",
    de: "Ausgabe",
    es: "Salida",
    fr: "Sortie",
    ja: "アウトプット",
    ko: "출력",
    pt: "Saída",
    ru: "Выход",
    zh: "输出",
  },
  // catur_wara / kanda_pat (four inner voices)
  EMOTION: {
    id: "Emosi",
    de: "Emotion",
    es: "Emoción",
    fr: "Émotion",
    ja: "感情",
    ko: "감정",
    pt: "Emoção",
    ru: "Эмоция",
    zh: "情感",
  },
  INTELLIGENCE: {
    id: "Kecerdasan",
    de: "Intelligenz",
    es: "Inteligencia",
    fr: "Intelligence",
    ja: "知性",
    ko: "지성",
    pt: "Inteligência",
    ru: "Интеллект",
    zh: "智慧",
  },
  CONSCIENCE: {
    id: "Hati Nurani",
    de: "Gewissen",
    es: "Conciencia",
    fr: "Conscience",
    ja: "良心",
    ko: "양심",
    pt: "Consciência",
    ru: "Совесть",
    zh: "良知",
  },
  INSTINCT: {
    id: "Insting",
    de: "Instinkt",
    es: "Instinto",
    fr: "Instinct",
    ja: "本能",
    ko: "본능",
    pt: "Instinto",
    ru: "Инстинкт",
    zh: "本能",
  },
  // panca_tirta (five vital organs)
  LIVER: {
    id: "Hati",
    de: "Leber",
    es: "Hígado",
    fr: "Foie",
    ja: "肝臓",
    ko: "간",
    pt: "Fígado",
    ru: "Печень",
    zh: "肝",
  },
  HEART: {
    id: "Jantung",
    de: "Herz",
    es: "Corazón",
    fr: "Cœur",
    ja: "心臓",
    ko: "심장",
    pt: "Coração",
    ru: "Сердце",
    zh: "心",
  },
  SPLEEN: {
    id: "Limpa",
    de: "Milz",
    es: "Bazo",
    fr: "Rate",
    ja: "脾臓",
    ko: "비장",
    pt: "Baço",
    ru: "Селезёнка",
    zh: "脾",
  },
  LUNG: {
    id: "Paru-paru",
    de: "Lunge",
    es: "Pulmón",
    fr: "Poumon",
    ja: "肺",
    ko: "폐",
    pt: "Pulmão",
    ru: "Лёгкие",
    zh: "肺",
  },
  KIDNEY: {
    id: "Ginjal",
    de: "Niere",
    es: "Riñón",
    fr: "Rein",
    ja: "腎臓",
    ko: "신장",
    pt: "Rim",
    ru: "Почка",
    zh: "肾",
  },
  // panca_brahma (five digestive organs)
  "LARGE INTESTINE": {
    id: "Usus Besar",
    de: "Dickdarm",
    es: "Intestino grueso",
    fr: "Gros intestin",
    ja: "大腸",
    ko: "대장",
    pt: "Intestino grosso",
    ru: "Толстая кишка",
    zh: "大肠",
  },
  BLADDER: {
    id: "Kandung Kemih",
    de: "Blase",
    es: "Vejiga",
    fr: "Vessie",
    ja: "膀胱",
    ko: "방광",
    pt: "Bexiga",
    ru: "Мочевой пузырь",
    zh: "膀胱",
  },
  GALLBLADDER: {
    id: "Kandung Empedu",
    de: "Gallenblase",
    es: "Vesícula biliar",
    fr: "Vésicule biliaire",
    ja: "胆嚢",
    ko: "담낭",
    pt: "Vesícula biliar",
    ru: "Желчный пузырь",
    zh: "胆囊",
  },
  "SMALL INTESTINE": {
    id: "Usus Halus",
    de: "Dünndarm",
    es: "Intestino delgado",
    fr: "Intestin grêle",
    ja: "小腸",
    ko: "소장",
    pt: "Intestino delgado",
    ru: "Тонкая кишка",
    zh: "小肠",
  },
  STOMACH: {
    id: "Lambung",
    de: "Magen",
    es: "Estómago",
    fr: "Estomac",
    ja: "胃",
    ko: "위",
    pt: "Estômago",
    ru: "Желудок",
    zh: "胃",
  },
  // dasa_aksara (ten cosmic forces)
  "DEITY/YANG": {
    id: "Dewa/Yang",
    de: "Gottheit/Yang",
    es: "Deidad/Yang",
    fr: "Divinité/Yang",
    ja: "神/陽",
    ko: "신/양",
    pt: "Divindade/Yang",
    ru: "Божество/Ян",
    zh: "神/阳",
  },
  HUMAN: {
    id: "Manusia",
    de: "Mensch",
    es: "Humano",
    fr: "Humain",
    ja: "人間",
    ko: "인간",
    pt: "Humano",
    ru: "Человек",
    zh: "人",
  },
  GIANT: {
    id: "Raksasa",
    de: "Riese",
    es: "Gigante",
    fr: "Géant",
    ja: "巨人",
    ko: "거인",
    pt: "Gigante",
    ru: "Великан",
    zh: "巨人",
  },
  DEITY: {
    id: "Dewa",
    de: "Gottheit",
    es: "Deidad",
    fr: "Divinité",
    ja: "神",
    ko: "신",
    pt: "Divindade",
    ru: "Божество",
    zh: "神",
  },
  "BRAHMA/YANG": {
    id: "Brahma/Yang",
    de: "Brahma/Yang",
    es: "Brahma/Yang",
    fr: "Brahma/Yang",
    ja: "ブラフマー/陽",
    ko: "브라흐마/양",
    pt: "Brahma/Yang",
    ru: "Брахма/Ян",
    zh: "梵天/阳",
  },
  KALA: {
    id: "Kala",
    de: "Kala",
    es: "Kala",
    fr: "Kala",
    ja: "カラ",
    ko: "칼라",
    pt: "Kala",
    ru: "Кала",
    zh: "时间神",
  },
  UMA: {
    id: "Uma",
    de: "Uma",
    es: "Uma",
    fr: "Uma",
    ja: "ウマ",
    ko: "우마",
    pt: "Uma",
    ru: "Ума",
    zh: "乌玛",
  },
  SRI: {
    id: "Sri",
    de: "Sri",
    es: "Sri",
    fr: "Sri",
    ja: "スリ",
    ko: "스리",
    pt: "Sri",
    ru: "Шри",
    zh: "吉祥天",
  },
  "WATER/YIN": {
    id: "Air/Yin",
    de: "Wasser/Yin",
    es: "Agua/Yin",
    fr: "Eau/Yin",
    ja: "水/陰",
    ko: "물/음",
    pt: "Água/Yin",
    ru: "Вода/Инь",
    zh: "水/阴",
  },
  // urip (energy value label)
  urip: {
    id: "urip",
    de: "Urip",
    es: "urip",
    fr: "urip",
    ja: "エネルギー値",
    ko: "에너지값",
    pt: "urip",
    ru: "урип",
    zh: "能量值",
  },
  // sapta_wara (day names)
  SATURDAY: {
    id: "Sabtu",
    de: "Samstag",
    es: "Sábado",
    fr: "Samedi",
    ja: "土曜日",
    ko: "토요일",
    pt: "Sábado",
    ru: "Суббота",
    zh: "星期六",
  },
  FRIDAY: {
    id: "Jumat",
    de: "Freitag",
    es: "Viernes",
    fr: "Vendredi",
    ja: "金曜日",
    ko: "금요일",
    pt: "Sexta-feira",
    ru: "Пятница",
    zh: "星期五",
  },
  THURSDAY: {
    id: "Kamis",
    de: "Donnerstag",
    es: "Jueves",
    fr: "Jeudi",
    ja: "木曜日",
    ko: "목요일",
    pt: "Quinta-feira",
    ru: "Четверг",
    zh: "星期四",
  },
  WEDNESDAY: {
    id: "Rabu",
    de: "Mittwoch",
    es: "Miércoles",
    fr: "Mercredi",
    ja: "水曜日",
    ko: "수요일",
    pt: "Quarta-feira",
    ru: "Среда",
    zh: "星期三",
  },
  TUESDAY: {
    id: "Selasa",
    de: "Dienstag",
    es: "Martes",
    fr: "Mardi",
    ja: "火曜日",
    ko: "화요일",
    pt: "Terça-feira",
    ru: "Вторник",
    zh: "星期二",
  },
  MONDAY: {
    id: "Senin",
    de: "Montag",
    es: "Lunes",
    fr: "Lundi",
    ja: "月曜日",
    ko: "월요일",
    pt: "Segunda-feira",
    ru: "Понедельник",
    zh: "星期一",
  },
  SUNDAY: {
    id: "Minggu",
    de: "Sonntag",
    es: "Domingo",
    fr: "Dimanche",
    ja: "日曜日",
    ko: "일요일",
    pt: "Domingo",
    ru: "Воскресенье",
    zh: "星期日",
  },
  // panca_wara (5-day market cycle - Balinese names, transliterated for CJK)
  PAHING: {
    id: "Pahing",
    de: "Pahing",
    es: "Pahing",
    fr: "Pahing",
    ja: "パヒン",
    ko: "파힝",
    pt: "Pahing",
    ru: "Пахинг",
    zh: "帕欣",
  },
  UMANIS: {
    id: "Umanis",
    de: "Umanis",
    es: "Umanis",
    fr: "Umanis",
    ja: "ウマニス",
    ko: "우마니스",
    pt: "Umanis",
    ru: "Уманис",
    zh: "乌曼尼斯",
  },
  KLIWON: {
    id: "Kliwon",
    de: "Kliwon",
    es: "Kliwon",
    fr: "Kliwon",
    ja: "クリウォン",
    ko: "클리원",
    pt: "Kliwon",
    ru: "Кливон",
    zh: "克利翁",
  },
  WAGE: {
    id: "Wage",
    de: "Wage",
    es: "Wage",
    fr: "Wage",
    ja: "ワゲ",
    ko: "와게",
    pt: "Wage",
    ru: "Ваге",
    zh: "瓦格",
  },
  PON: {
    id: "Pon",
    de: "Pon",
    es: "Pon",
    fr: "Pon",
    ja: "ポン",
    ko: "폰",
    pt: "Pon",
    ru: "Пон",
    zh: "蓬",
  },
  // sad_wara (6-day cycle - Balinese names, transliterated for CJK)
  ARIYANG: {
    id: "Ariyang",
    de: "Ariyang",
    es: "Ariyang",
    fr: "Ariyang",
    ja: "アリヤン",
    ko: "아리양",
    pt: "Ariyang",
    ru: "Ариянг",
    zh: "阿里扬",
  },
  TUNGLEH: {
    id: "Tungleh",
    de: "Tungleh",
    es: "Tungleh",
    fr: "Tungleh",
    ja: "トゥンレ",
    ko: "퉁레",
    pt: "Tungleh",
    ru: "Тунгле",
    zh: "通勒",
  },
  MAULU: {
    id: "Maulu",
    de: "Maulu",
    es: "Maulu",
    fr: "Maulu",
    ja: "マウル",
    ko: "마울루",
    pt: "Maulu",
    ru: "Маулу",
    zh: "马乌卢",
  },
  WAS: {
    id: "Was",
    de: "Was",
    es: "Was",
    fr: "Was",
    ja: "ワス",
    ko: "와스",
    pt: "Was",
    ru: "Вас",
    zh: "瓦斯",
  },
  PANIRON: {
    id: "Paniron",
    de: "Paniron",
    es: "Paniron",
    fr: "Paniron",
    ja: "パニロン",
    ko: "파니론",
    pt: "Paniron",
    ru: "Панирон",
    zh: "帕尼龙",
  },
  URUKUNG: {
    id: "Urukung",
    de: "Urukung",
    es: "Urukung",
    fr: "Urukung",
    ja: "ウルクン",
    ko: "우루쿵",
    pt: "Urukung",
    ru: "Урукунг",
    zh: "乌鲁恭",
  },
  // wuku (30 Balinese calendar weeks - transliterated for CJK)
  WARIGADEAN: {
    id: "Warigadean",
    de: "Warigadean",
    es: "Warigadean",
    fr: "Warigadean",
    ja: "ワリガデアン",
    ko: "와리가데안",
    pt: "Warigadean",
    ru: "Варигадеан",
    zh: "瓦里加迪安",
  },
  WARIGA: {
    id: "Wariga",
    de: "Wariga",
    es: "Wariga",
    fr: "Wariga",
    ja: "ワリガ",
    ko: "와리가",
    pt: "Wariga",
    ru: "Варига",
    zh: "瓦里加",
  },
  GUMBREG: {
    id: "Gumbreg",
    de: "Gumbreg",
    es: "Gumbreg",
    fr: "Gumbreg",
    ja: "グンブレグ",
    ko: "굼브렉",
    pt: "Gumbreg",
    ru: "Гумбрег",
    zh: "贡布雷格",
  },
  TOLU: {
    id: "Tolu",
    de: "Tolu",
    es: "Tolu",
    fr: "Tolu",
    ja: "トル",
    ko: "톨루",
    pt: "Tolu",
    ru: "Толу",
    zh: "托卢",
  },
  KULANTIR: {
    id: "Kulantir",
    de: "Kulantir",
    es: "Kulantir",
    fr: "Kulantir",
    ja: "クランティル",
    ko: "쿨란티르",
    pt: "Kulantir",
    ru: "Кулантир",
    zh: "库兰提尔",
  },
  UKIR: {
    id: "Ukir",
    de: "Ukir",
    es: "Ukir",
    fr: "Ukir",
    ja: "ウキル",
    ko: "우키르",
    pt: "Ukir",
    ru: "Укир",
    zh: "乌基尔",
  },
  LANDEP: {
    id: "Landep",
    de: "Landep",
    es: "Landep",
    fr: "Landep",
    ja: "ランデプ",
    ko: "란덥",
    pt: "Landep",
    ru: "Ландеп",
    zh: "兰德普",
  },
  SINTA: {
    id: "Sinta",
    de: "Sinta",
    es: "Sinta",
    fr: "Sinta",
    ja: "シンタ",
    ko: "신타",
    pt: "Sinta",
    ru: "Синта",
    zh: "辛塔",
  },
  WATUGUNUNG: {
    id: "Watugunung",
    de: "Watugunung",
    es: "Watugunung",
    fr: "Watugunung",
    ja: "ワトゥグヌン",
    ko: "와투구눙",
    pt: "Watugunung",
    ru: "Ватугунунг",
    zh: "瓦图古农",
  },
  DUKUT: {
    id: "Dukut",
    de: "Dukut",
    es: "Dukut",
    fr: "Dukut",
    ja: "ドゥクット",
    ko: "두쿳",
    pt: "Dukut",
    ru: "Дукут",
    zh: "杜库特",
  },
  KELAWU: {
    id: "Kelawu",
    de: "Kelawu",
    es: "Kelawu",
    fr: "Kelawu",
    ja: "クラウ",
    ko: "클라우",
    pt: "Kelawu",
    ru: "Келаву",
    zh: "克拉乌",
  },
  WAYANG: {
    id: "Wayang",
    de: "Wayang",
    es: "Wayang",
    fr: "Wayang",
    ja: "ワヤン",
    ko: "와양",
    pt: "Wayang",
    ru: "Ваянг",
    zh: "哇扬",
  },
  UGU: {
    id: "Ugu",
    de: "Ugu",
    es: "Ugu",
    fr: "Ugu",
    ja: "ウグ",
    ko: "우구",
    pt: "Ugu",
    ru: "Угу",
    zh: "乌古",
  },
  BALA: {
    id: "Bala",
    de: "Bala",
    es: "Bala",
    fr: "Bala",
    ja: "バラ",
    ko: "발라",
    pt: "Bala",
    ru: "Бала",
    zh: "巴拉",
  },
  PERANGBAKAT: {
    id: "Perangbakat",
    de: "Perangbakat",
    es: "Perangbakat",
    fr: "Perangbakat",
    ja: "ペランバカット",
    ko: "페랑바캇",
    pt: "Perangbakat",
    ru: "Перангбакат",
    zh: "佩朗巴卡特",
  },
  MENAIL: {
    id: "Menail",
    de: "Menail",
    es: "Menail",
    fr: "Menail",
    ja: "ムナイル",
    ko: "므나일",
    pt: "Menail",
    ru: "Менаил",
    zh: "梅奈尔",
  },
  UYE: {
    id: "Uye",
    de: "Uye",
    es: "Uye",
    fr: "Uye",
    ja: "ウイェ",
    ko: "우예",
    pt: "Uye",
    ru: "Уйе",
    zh: "乌耶",
  },
  MATAL: {
    id: "Matal",
    de: "Matal",
    es: "Matal",
    fr: "Matal",
    ja: "マタル",
    ko: "마탈",
    pt: "Matal",
    ru: "Матал",
    zh: "马塔尔",
  },
  MEDANGKUNGAN: {
    id: "Medangkungan",
    de: "Medangkungan",
    es: "Medangkungan",
    fr: "Medangkungan",
    ja: "ムダンクンガン",
    ko: "므당꿍안",
    pt: "Medangkungan",
    ru: "Медангкунган",
    zh: "梅当昆安",
  },
  TAMBIR: {
    id: "Tambir",
    de: "Tambir",
    es: "Tambir",
    fr: "Tambir",
    ja: "タンビル",
    ko: "탐비르",
    pt: "Tambir",
    ru: "Тамбир",
    zh: "坦比尔",
  },
  MERAKIH: {
    id: "Merakih",
    de: "Merakih",
    es: "Merakih",
    fr: "Merakih",
    ja: "ムラキ",
    ko: "므라키",
    pt: "Merakih",
    ru: "Мераких",
    zh: "梅拉基",
  },
  KRULUT: {
    id: "Krulut",
    de: "Krulut",
    es: "Krulut",
    fr: "Krulut",
    ja: "クルルット",
    ko: "크룰룻",
    pt: "Krulut",
    ru: "Крулут",
    zh: "克鲁卢特",
  },
  PAHANG: {
    id: "Pahang",
    de: "Pahang",
    es: "Pahang",
    fr: "Pahang",
    ja: "パハン",
    ko: "파항",
    pt: "Pahang",
    ru: "Паханг",
    zh: "巴杭",
  },
  PUJUT: {
    id: "Pujut",
    de: "Pujut",
    es: "Pujut",
    fr: "Pujut",
    ja: "プジュット",
    ko: "푸줏",
    pt: "Pujut",
    ru: "Пуджут",
    zh: "普朱特",
  },
  MEDANGSIA: {
    id: "Medangsia",
    de: "Medangsia",
    es: "Medangsia",
    fr: "Medangsia",
    ja: "ムダンシア",
    ko: "므당시아",
    pt: "Medangsia",
    ru: "Медангсиа",
    zh: "梅当西亚",
  },
  LANGKIR: {
    id: "Langkir",
    de: "Langkir",
    es: "Langkir",
    fr: "Langkir",
    ja: "ランキル",
    ko: "랑키르",
    pt: "Langkir",
    ru: "Лангкир",
    zh: "兰基尔",
  },
  KUNINGAN: {
    id: "Kuningan",
    de: "Kuningan",
    es: "Kuningan",
    fr: "Kuningan",
    ja: "クニンガン",
    ko: "쿠닝안",
    pt: "Kuningan",
    ru: "Кунинган",
    zh: "库宁安",
  },
  DUNGULAN: {
    id: "Dungulan",
    de: "Dungulan",
    es: "Dungulan",
    fr: "Dungulan",
    ja: "ドゥングラン",
    ko: "둥울란",
    pt: "Dungulan",
    ru: "Дунгулан",
    zh: "敦古兰",
  },
  SUNGSANG: {
    id: "Sungsang",
    de: "Sungsang",
    es: "Sungsang",
    fr: "Sungsang",
    ja: "スンサン",
    ko: "숭상",
    pt: "Sungsang",
    ru: "Сунгсанг",
    zh: "松桑",
  },
  JULUNGWANGI: {
    id: "Julungwangi",
    de: "Julungwangi",
    es: "Julungwangi",
    fr: "Julungwangi",
    ja: "ジュルンワンギ",
    ko: "줄룽왕이",
    pt: "Julungwangi",
    ru: "Джулунгванги",
    zh: "朱隆旺吉",
  },
};
