import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  container: { flex: 1 },
  scroll: { flex: 1 },
  headerSection: { paddingHorizontal: 20, marginBottom: 16 },
  screenTitle: { fontSize: 28, fontWeight: "900", letterSpacing: 0.3 },
  card: {
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
  },
  cardTitle: { fontSize: 16, fontWeight: "700", marginBottom: 12 },
  cardTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  cardSubtitle: { fontSize: 12, marginBottom: 12 },
  avatarRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { fontSize: 24 },
  avatarInfo: { flex: 1 },
  nameText: { fontSize: 20, fontWeight: "800" },
  addressText: { fontSize: 13, fontFamily: "monospace", marginTop: 2 },
  lockedRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  lockIcon: { fontSize: 14 },
  eyeIcon: { fontSize: 14, marginLeft: 8 },
  hint: { fontSize: 11, marginTop: 4, fontStyle: "italic" },
  dateButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 4,
  },
  dateIcon: { fontSize: 16 },
  warning: { fontSize: 11, marginTop: 6, lineHeight: 16 },
  actionButton: {
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    marginTop: 8,
  },
  actionButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" },
  interestGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  interestChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1.5,
  },
  interestIcon: { fontSize: 16 },
  interestLabel: { fontSize: 12 },
  interestCount: { fontSize: 13, fontWeight: "600" },
  toggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  settingLabel: { fontSize: 14, fontWeight: "500" },
  settingValue: { fontSize: 15 },
  settingValueMono: { fontSize: 14, fontFamily: "monospace" },
  currentLang: { fontSize: 14, marginBottom: 8 },
  langGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  langButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  langFlag: { fontSize: 16 },
  langLabel: { fontSize: 12 },
  langLabelActive: { fontWeight: "600" },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  networkBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  networkBadgeText: {
    fontSize: 12,
    fontWeight: "700",
  },
  disconnectButton: {
    marginHorizontal: 16,
    marginTop: 8,
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
  },
  disconnectText: { fontSize: 14, fontWeight: "700" },
});
